### ISSUE TITLE
I got error on PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by pom12097** [BG-Software-LLC/WildStacker#144]
**Minecraft's Version**
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Plugin's Version**: -
WildStacker v3.5.2

**Describe the bug**

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
[16:49:04] [Server thread/WARN]: [WildStacker] Task #9430043 for WildStacker v3.5.2 generated an exception
java.lang.NullPointerException: name
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayOutNamedSoundEffect.<init>(SourceFile:28) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:28) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.World.makeSound(World.java:945) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.Entity.makeSound(Entity.java:824) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_8_R3.playDeathSound(NMSAdapter_v1_8_R3.java:396) ~[?:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.lambda$runUnstack$8(WStackedEntity.java:428) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
