### ISSUE TITLE
NullPointerException - TileEntity threw exception at world

### ISSUE THREAD

**Issue by MedicOP** [BG-Software-LLC/WildStacker#147]
[07:37:47 WARN]: TileEntity threw exception at world:2507,42,-1248
[07:37:47 WARN]: java.lang.NullPointerException
[07:37:47 WARN]:        at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
[07:37:47 WARN]:        at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
[07:37:47 WARN]:        at java.util.Collections$SetFromMap.remove(Collections.java:5460)
[07:37:47 WARN]:        at com.bgsoftware.wildstacker.handlers.SystemHandler.markToBeUnsaved(SystemHandler.java:461)
[07:37:47 WARN]:        at com.bgsoftware.wildstacker.handlers.SystemHandler.removeStackObject(SystemHandler.java:120)
[07:37:47 WARN]:        at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_8_R3$StackedMobSpawner.handleEntitySpawn(NMSSpawners_v1_8_R3.java:518)
[07:37:47 WARN]:        at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_8_R3$StackedMobSpawner.c(NMSSpawners_v1_8_R3.java:441)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.TileEntityMobSpawner.c(TileEntityMobSpawner.java:40)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:3161)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:635)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1175)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:370)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:818)
[07:37:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:719)
[07:37:47 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Skizzles** [comment]
@MedicOP Please provide what build of WildStacker you are using and make sure to follow the format in the future.

**Comment by MedicOP** [comment]
Latest dev build, problems disappears after disabling "spawner-override"

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
