### ISSUE TITLE
[WildStacker] Task #53411259 for WildStacker v3.5.2-DEVb114 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by LynxError** [BG-Software-LLC/WildStacker#153]
[11:41:31] [Server thread/WARN]: [WildStacker] Task #53411259 for WildStacker v3.5.2-DEVb114 generated an exception
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:440) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener$$Lambda$6757/0x00000000482621b0.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/000000000000000000.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]

**Comment by MZhenkM** [comment]
Server version? Config? Reproduction?

**Comment by LynxError** [comment]
updated paper to 605 MC 1.16.5 still get error, did a fresh clean install, no changes to config and it still gens error

[20:55:43] [Server thread/WARN]: [WildStacker] Task #1118946 for WildStacker v3.5.2-DEVb114 generated an exception
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:440) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener$$Lambda$6737/0x0000000048ea18c0.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/000000000000000000.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]

**Comment by OmerBenGera** [comment]
Mind taking the error again when using b115?

**Comment by OmerBenGera** [comment]
??

**Comment by LynxError** [comment]
Sorry for the Delay, yes 116 is no errors, I will try 117/118

**Comment by OmerBenGera** [comment]
Great, if there are no errors anymore make sure you close the issue :)

**Comment by Skizzles** [comment]
Getting this issue on b118

[15:28:22] [Server thread/WARN]: [WildStacker] Task #13576782 for WildStacker v3.5.2-DEVb118 generated an exception
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:440) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1067]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1067]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1499) ~[patched_1.16.5.jar:git-Purpur-1067]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:433) ~[patched_1.16.5.jar:git-Purpur-1067]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1067]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1067]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1067]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LynxError** [comment]
117 no issues, updating to 118 and paper 660 tonight, if no errors, i will post, but b117 & paper 629 no issues

**Comment by LynxError** [comment]
Error Back
[12:03:21] [Server thread/WARN]: [WildStacker] Task #282960 for WildStacker v3.5.2-DEVb118 generated an exception
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:440) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener$$Lambda$7089/0x00000000491d3830.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-658]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-658]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/000000000000000000.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]

**Comment by LynxError** [comment]
Upgraded to Paper 658

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it works

**Comment by OmerBenGera** [comment]
I pushed another fix for it. Also, we'll move to #171
