### ISSUE TITLE
server crashes if citizens is disabled

### ISSUE THREAD

**Issue by MedicOP** [BG-Software-LLC/WildStacker#160]
```[13-05-2021 12:22:51] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.16-SNAPSHOT (build Unknown)
[13-05-2021 12:22:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world entities
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1225) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:370) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:822) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:723) [WineSpigot.jar:1_8_R3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/Citizens
	at com.bgsoftware.wildstacker.hooks.CitizensHook.isNPC(CitizensHook.java:16) ~[?:?]
	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.isStackable(EntityUtils.java:145) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityRemove(EntitiesListener.java:912) ~[?:?]
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_8_R3$2.b(NMSAdapter_v1_8_R3.java:453) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.b(World.java:1894) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:1197) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:3072) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:729) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1214) ~[WineSpigot.jar:1_8_R3]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.Citizens
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[WineSpigot.jar:1_8_R3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[WineSpigot.jar:1_8_R3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at com.bgsoftware.wildstacker.hooks.CitizensHook.isNPC(CitizensHook.java:16) ~[?:?]
	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.isStackable(EntityUtils.java:145) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityRemove(EntitiesListener.java:912) ~[?:?]
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_8_R3$2.b(NMSAdapter_v1_8_R3.java:453) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.b(World.java:1894) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:1197) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:3072) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:729) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1214) ~[WineSpigot.jar:1_8_R3]
	... 4 more
[13-05-2021 12:22:51] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoClassDefFoundError: net/citizensnpcs/Citizens
	at com.bgsoftware.wildstacker.hooks.CitizensHook.isNPC(CitizensHook.java:16) ~[?:?]
	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.isStackable(EntityUtils.java:145) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityRemove(EntitiesListener.java:912) ~[?:?]
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_8_R3$2.b(NMSAdapter_v1_8_R3.java:453) ~[?:?]
	at net.minecraft.server.v1_8_R3.World.b(World.java:1894) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:1197) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:3072) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:729) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1214) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:370) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:822) ~[WineSpigot.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:723) [WineSpigot.jar:1_8_R3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.Citizens
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[WineSpigot.jar:1_8_R3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[WineSpigot.jar:1_8_R3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 13 more
[13-05-2021 12:22:51] [Server thread/ERROR]: This crash report has been saved to: asdasd.txt
[13-05-2021 12:22:51] [Server thread/INFO]: Stopping server```

**Comment by OmerBenGera** [comment]
Did you have Citizens installed and then you disabled it?

**Comment by MedicOP** [comment]
yep

**Comment by OmerBenGera** [comment]
This is not supported. You must have a full restart in order to take such actions

**Comment by MedicOP** [comment]
none of my 200 other plugins crash when doing this, there's a plugindisableevent for a reason

**Comment by OmerBenGera** [comment]
As I said before, its not supported and you should not use plugman.
