### ISSUE TITLE
CreatureSpawnEvent NullPointer - GetTurtleHome

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#164]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
Dev Build 118

**Describe the bug**
When attempting to Spawn turtles from a spawner this error is thrown and they do not spawn.

**To Reproduce**
Place Turtle spawner
Try to spawn turtles

**Additional information**
[07:53:08] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2-DEVb118
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R3.DataWatcher.get(DataWatcher.java:130) ~[patched_1.16.5.jar:git-Purpur-1086]
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_16_R3.getTurtleHome(NMSAdapter_v1_16_R3.java:393) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntitySpawn(EntitiesListener.java:957) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawn(EntitiesListener.java:527) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1461.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1086]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1086]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1086]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1086]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:727) ~[patched_1.16.5.jar:git-Purpur-1086]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:648) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1933) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1834) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.BlockTurtleEgg.tick(BlockTurtleEgg.java:136) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.b(BlockBase.java:681) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:1380) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:950) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1059) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1563) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:433) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1086]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1086]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
