### ISSUE TITLE
Random Error in console

### ISSUE THREAD

**Issue by TenReeez** [BG-Software-LLC/WildStacker#165]
1.13.2 Paper

Version: B110

Random error in console. I have no idea why or how.

I dont know how. Sorry

More of a report, then needing a fix.

00:57:23] [Craft Scheduler Thread - 255/WARN]: [WildStacker] Plugin WildStacker v3.5.2-DEVb110 generated an exception while executing task 192
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at net.minecraft.server.v1_13_R2.World.getType(World.java:810) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:182) ~[patched_1.13.2.jar:git-Paper-655]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.isStackedSpawner(SystemHandler.java:348) ~[?:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.performCacheClear(SystemHandler.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-655]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-655]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by OmerBenGera** [comment]
Use latest dev build, should be fixed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by TenReeez** [comment]
Hello. No I have been awol will check in the next 48hours. thank you

**Comment by OmerBenGera** [comment]
Any news regarding this?
