### ISSUE TITLE
Could not pass event CreatureSpawnEvent to WildStacker v3.5.2

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/WildStacker#171]
**Minecraft's Version**
This server is running Purpur version git-Purpur-1118 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**:  - 3.5.2

**Describe the bug**
Random dropping an error message, don't know what is the cause of that message.

**To Reproduce**
I don't know

**Additional information**

Pastebin link: https://pastebin.com/K1j2bBcQ

**Comment by OmerBenGera** [comment]
Use latest dev build. If the issue persists, make sure you let me know here

**Comment by rentexfamily** [comment]
Can you send me a link for lastest devbuild, i have 3.5.2 what is lastest I can see ?

**Comment by OmerBenGera** [comment]
You can find it on https://bg-software.com/wildstacker

**Comment by rentexfamily** [comment]
Still have bug.


[19:00:11 ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.bgsoftware.wildstacker.api.objects.StackedEntity.getFlag(com.bgsoftware.wildstacker.api.enums.EntityFlag)" is null
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntitySpawnLow$7(EntitiesListener.java:520) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:176) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLow(EntitiesListener.java:518) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1123]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1123]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1123]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Purpur-1123]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:731) ~[patched_1.16.5.jar:git-Purpur-1123]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:649) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1934) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1835) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:323) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:568) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:443) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:316) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:594) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2612) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:404) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:216) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1540) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1144) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1564) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1123]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1123]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by OmerBenGera** [comment]
Try latest dev build, let me know if it still occurs

**Comment by rezz506** [comment]
Okay so I was also previously getting this error in console. Updated to latest dev build and is still happening again - but not as much as it was previously. It was spamming "[20:33:41 ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2
java.lang.NullPointerException: null"

I don't know if they are related but I did some investigating on my server and found that players are farming blaze when this error pops up in the console. 

Running Paper version 1.16.5-706

**Comment by rezz506** [comment]
Follow up: It is now spamming the console when players use a naturally generating magma farm in the nether.

**Comment by OmerBenGera** [comment]
check out latest dev build, hopefully it's fixed in this version

**Comment by rezz506** [comment]
This seems to be resolved with the latest build. 
Will comment again if errors consist.

**Comment by OmerBenGera** [comment]
Perfect :)
