### ISSUE TITLE
InventoryPickupItemEvent Error

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#182]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.16.5 Purpur

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
Wildstacker 3.5.2 dev 123

**Describe the bug**
Error being spammed in console

**To Reproduce**
Steps to reproduce the bug.
Not able to find reason why.

**Additional information**
```
[08:39:27] [Server thread/ERROR]: Could not pass event InventoryPickupItemEvent to WildStacker v3.5.2-DEVb123
java.lang.IllegalArgumentException: size is too large
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Purpur-1149]
	at gg.airplane.structs.ItemListWithBitset.<init>(ItemListWithBitset.java:40) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.TileEntityChest.load(TileEntityChest.java:120) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.copyData(CraftBlockEntityState.java:90) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.applyTo(CraftBlockEntityState.java:131) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftContainer.applyTo(CraftContainer.java:61) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftLootable.applyTo(CraftLootable.java:25) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftLootable.applyTo(CraftLootable.java:13) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.update(CraftBlockEntityState.java:147) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState.update(CraftBlockState.java:162) ~[patched_1.16.5.jar:git-Purpur-1149]
	at com.bgsoftware.wildstacker.listeners.ItemsListener.onInventoryPickup(ItemsListener.java:226) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1503.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1149]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1149]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.a(TileEntityHopper.java:576) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.a(TileEntityHopper.java:519) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.lambda$tick$0(TileEntityHopper.java:163) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.a(TileEntityHopper.java:184) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.TileEntityHopper.tick(TileEntityHopper.java:162) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:1083) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1220) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1567) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:451) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1149]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1149]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by OmerBenGera** [comment]
Do you have fix-stack disabled in the config?

**Comment by OmerBenGera** [comment]
Any news regarding this?
