### ISSUE TITLE
Bug on spawning IronGolem

### ISSUE THREAD

**Issue by xsorencoolx** [BG-Software-LLC/WildStacker#187]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
#134

**Describe the bug**
the bug is really weird sometimes the iron golem spawner wont spawn like it stuck at 0s or it right there are no nearby players 
but there are players around the spawner

**Comment by OmerBenGera** [comment]
Spunds like the spawner cant find a place to spawn the mobs. Make sure you place enough blocks so they can spawn, or change the spawn conditions of the spawners.

**Comment by xsorencoolx** [comment]
![Screenshot (553)](https://user-images.githubusercontent.com/51112473/121525384-1db72880-c9ad-11eb-9b2c-5300886b6bee.png)
![Screenshot (554)](https://user-images.githubusercontent.com/51112473/121525393-20b21900-c9ad-11eb-95e2-5c51aabb652f.png)
just wanted to show you this

**Comment by xsorencoolx** [comment]
[10:47:24 ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2
java.lang.NullPointerException: null
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntity
SpawnLow$7(EntitiesListener.java:520) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLo
w(EntitiesListener.java:518) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
ecutor158.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69
) ~[patched_1.16.5.jar:git-Purpur-1051]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:8
0) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:607) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureS
pawnEvent(CraftEventFactory.java:713) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEv
entCalling(CraftEventFactory.java:634) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java
:1935) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:
1836) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:323) ~
[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:568)
~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLivin
g.java:443) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityI
nsentient.java:318) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:564) ~[patched_
1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:258
7) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.
java:406) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:216)
~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServ
er.java:1541) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:114
2) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:
1554) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:
430) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:
1403) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:
1129) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftSer
ver.java:291) ~[patched_1.16.5.jar:git-Purpur-1051]
        at java.lang.Thread.run(Thread.java:834) [?:?]


and sometimes it shows this in console

**Comment by OmerBenGera** [comment]
> 
> 
> ![Screenshot (553)](https://user-images.githubusercontent.com/51112473/121525384-1db72880-c9ad-11eb-9b2c-5300886b6bee.png)
> ![Screenshot (554)](https://user-images.githubusercontent.com/51112473/121525393-20b21900-c9ad-11eb-95e2-5c51aabb652f.png)
> just wanted to show you this

If you don't override the spawn conditions, by default, mobs can't spawn in air.
You might want to override the spawn conditions for iron golems so they can spawn in air.
