### ISSUE TITLE
Error Could not pass event CreatureSpawnEvent to WildStacker v3.5.2

### ISSUE THREAD

**Issue by Ronal1999** [BG-Software-LLC/WildStacker#188]
That is the error, sorry for the spam

[23:42:34 ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2
java.lang.NullPointerException: null
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntitySpawnLow$7(EntitiesListener.java:520) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLow(EntitiesListener.java:518) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor977.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1161]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1161]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1161]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1161]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:734) ~[patched_1.16.5.jar:git-Purpur-1161]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:652) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1906) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1807) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:323) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:570) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:445) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:316) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:591) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2614) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:404) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:216) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1512) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.World.a(World.java:1072) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1567) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1161]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0

**Comment by OmerBenGera** [comment]
Update WildStacker to latest dev build
