### ISSUE TITLE
PlotSquared v6 API change

### ISSUE THREAD

**Issue by JasonHorkles** [BG-Software-LLC/WildStacker#205]
**Minecraft's Version**
This server is running Tuinity version git-Tuinity-"3a57f64" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Tuinity-"901ac35" (MC: 1.16.5)

**Plugin's Version**: -
3.6.0-DEVb143

**Describe the bug**
Warning is shown on startup because of the P2 v6 API changing
```accesslog
[13:05:02 WARN]: [WildStacker] Task #147 for WildStacker v3.6.0-DEVb143 generated an exception
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/api/PlotAPI
        at com.bgsoftware.wildstacker.hooks.ClaimsProvider_PlotSquaredLegacy.<init>(ClaimsProvider_PlotSquaredLegacy.java:10) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.loadClaimsProvider(ProvidersHandler.java:126) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:72) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Tuinity-"3a57f64"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Tuinity-"3a57f64"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1198) ~[patched_1.17.jar:git-Tuinity-"3a57f64"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.jar:git-Tuinity-"3a57f64"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.api.PlotAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Tuinity-"3a57f64"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Tuinity-"3a57f64"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 8 more
```

**To Reproduce**
Start the server with P2 v6 and WS and see the warning

**Additional information**
Config https://paste.gg/p/JasonHorkles/a4be72bc5da04befa2e6e4e3dda65b6e

**Comment by OmerBenGera** [comment]
I need access to the jar that you use.
Please open a ticket and send a copy of the jar there (If you don't have access, tag myself or one of my staff team so they open a ticket for you)

**Comment by OmerBenGera** [comment]
Fixed in latest dev (155)
