### ISSUE TITLE
Failed thread check

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#213]
**Minecraft's Version**
1.17 Purpur build 1240

**Plugin's Version**: -
Dev build 156

**Describe the bug**
Error spawn in console.

**To Reproduce**
Unknown, just spamming console

**Additional information**
[08:47:02 FATAL]: Thread Craft Scheduler Thread - 11 - WildStacker failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2368) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntitiesByClass(CraftWorld.java:1212) ~[patched_1.17.jar:git-Purpur-1240]
        at com.bgsoftware.wildstacker.tasks.ItemsMerger.run(ItemsMerger.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Purpur-1240]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.jar:git-Purpur-1240]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Purpur-1240]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Skizzles** [comment]
Duplicate of another issue.
