### ISSUE TITLE
Thread Craft Scheduler Thread - 5 - WildStacker failed thread check for reason: Asynchronous Chunk getEntities call java.lang.Throwable: null

### ISSUE THREAD

**Issue by xSavior-of-God** [BG-Software-LLC/WildStacker#216]
**Minecraft's Version**
1.17 Java 16 Airplane.io

**Plugin's Version**: -
dev 156

**Describe the bug**
Console Error SPAM
`[22:15:40 FATAL]: Thread Craft Scheduler Thread - 5 - WildStacker failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Airplane-38]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2361) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getLivingEntities(CraftWorld.java:1188) ~[patched_1.17.jar:git-Airplane-38]
        at com.bgsoftware.wildstacker.tasks.StackTask.run(StackTask.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Airplane-38]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.jar:git-Airplane-38]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Airplane-38]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**To Reproduce**
I updated my 1.16.5 old configuration and world to 1.17 and now i have this errors

**Additional information**
Airplane download Link
https://ci.tivy.ca/

**Comment by OmerBenGera** [comment]
Fixed in dev build 157 :)
