### ISSUE TITLE
Console Spam from Async Chunk getEntities

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#219]
**Minecraft's Version**
1.17.1 Purpur

**Plugin's Version**: -
dev b157

**Describe the bug**
Console spam

**To Reproduce**
N/A

**Additional information**
[02:32:01 FATAL]: Thread Craft Scheduler Thread - 47 - WildStacker failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2409) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntitiesByClass(CraftWorld.java:1212) ~[patched_1.17.1.jar:git-Purpur-1260]
        at com.bgsoftware.wildstacker.tasks.ItemsMerger.run(ItemsMerger.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1260]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1260]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[02:32:11 FATAL]: Thread Craft Scheduler Thread - 5 - WildStacker failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2409) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntitiesByClass(CraftWorld.java:1212) ~[patched_1.17.1.jar:git-Purpur-1260]
        at com.bgsoftware.wildstacker.tasks.ItemsMerger.run(ItemsMerger.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1260]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1260]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
