### ISSUE TITLE
ItemSpawnEvent Error

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#221]
**Minecraft's Version**
1.17.1

**Plugin's Version**: -
dev b160

**Describe the bug**
Error thrown still in console

**To Reproduce**
Spammed in console

**Additional information**
[16:19:05 ERROR]: Could not pass event ItemSpawnEvent to WildStacker v3.6.0-DEVb160
java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.getEggLayTime(NMSAdapter_v1_17_R1.java:321) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.events.EventsListener$EggLay.lambda$onEggLay$0(EventsListener.java:79) ~[?:?]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.lambda$getNearbyEntities$0(NMSAdapter_v1_17_R1.java:362) ~[?:?]
        at net.minecraft.world.level.entity.EntitySection.getEntities(EntitySection.java:50) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.level.entity.EntitySectionStorage.lambda$getEntities$2(EntitySectionStorage.java:128) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.level.entity.EntitySectionStorage.forEachAccessibleSection(EntitySectionStorage.java:56) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.level.entity.EntitySectionStorage.getEntities(EntitySectionStorage.java:126) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.level.entity.LevelEntityGetterAdapter.get(LevelEntityGetterAdapter.java:46) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.level.entity.LevelEntityGetterAdapter.get(LevelEntityGetterAdapter.java:42) ~[patched_1.17.1.jar:git-Purpur-1260]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.getNearbyEntities(NMSAdapter_v1_17_R1.java:361) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.EntitiesGetter.getNearbyEntities(EntitiesGetter.java:38) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.events.EventsListener$EggLay.onEggLay(EventsListener.java:78) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1260]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:746) ~[patched_1.17.1.jar:git-Purpur-1260]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:640) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1515) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1422) ~[?:?]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2418) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2386) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2381) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.world.entity.animal.Chicken.aiStep(Chicken.java:137) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2942) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:420) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1235) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1034) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:852) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:40) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:833) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1260]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1260]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build
