### ISSUE TITLE
there is an exception when i kill an entity

### ISSUE THREAD

**Issue by Symii** [BG-Software-LLC/WildStacker#227]
### Minecraft's Version

git-Paper-99 MC: 1.17.1

### Plugin's Version

WildStacker v3.6.0-DEVb163

### Describe the bug

there is an exception when i kill an entity (pillager, vindicator and evoker)

### To Reproduce

just kill pillager, vindicator or evoker (spawn mob using spawn egg)

### Additional Information

`[12:14:04] [Server thread/WARN]: [WildStacker] Task #26805 for WildStacker v3.6.0-DEVb163 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.bgsoftware.common.reflection.ReflectMethod.invoke(Object, Object[])" is null
at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.attemptJoinRaid(NMSAdapter_v1_17_R1.java:740) ~[?:?]
at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$4(EntitiesListener.java:497) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-99]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Paper-99]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-99]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-99]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-99]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-99]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-99]
at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
