### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Restland** [BG-Software-LLC/WildStacker#257]
### Minecraft's Version

1.16.5

### Plugin's Version

Minehut updates the plugin don't know exactly the version.

### Describe the bug

[Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntitySpawnLow$7(EntitiesListener.java:520) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLow(EntitiesListener.java:518) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor526.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-771]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:722) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:640) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1302) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1203) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:263) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:561) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:436) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:315) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:529) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:378) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:156) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.World.a(World.java:955) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-771]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[19:07:34] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.2
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntitySpawnLow$7(EntitiesListener.java:520) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLow(EntitiesListener.java:518) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor526.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-771]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:722) ~[patched_1.16.5.jar:git-Paper-771]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:640) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1302) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1203) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:263) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:561) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:436) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:315) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:529) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:378) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:156) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.World.a(World.java:955) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-771]
	at java.lang.Thread.run(Thread.java:829) [?:?]

### To Reproduce

It happens randomly.

**Comment by Restland** [comment]
Version : 3.5.2

**Comment by OmerBenGera** [comment]
Minehut dont support dev builds of the plugin. I recommend you to switch to another hosting service that lets you use custom jars so you can install latest dev build of the plugin.
