### ISSUE TITLE
Bug when plugin (MythicMobs) spawns end_crystals

### ISSUE THREAD

**Issue by ghtg** [BG-Software-LLC/WildStacker#302]
### Minecraft's Version

core: papermc 1.17.1

### Plugin's Version

WildStacker v3.6.0-DEVb203

### Describe the bug

Prints error in console

### To Reproduce

When plugin (MythicMobs) spawns end_crystals i'll get this error

[21:50:09 ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v3.6.0-DEVb203
java.lang.IllegalArgumentException: The entity-type ENDER_CRYSTAL is not a stackable entity.
        at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:80) ~[WildStacker-b203.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityNerfDamage(EntitiesListener.java:182) ~[WildStacker-b203.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-232]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:966) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:943) ~[patched_1.17.1.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1135) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2042) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1350) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.boss.wither.EntityWither.damageEntity(EntityWither.java:517) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.Explosion.a(Explosion.java:250) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.World.createExplosion(World.java:1017) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.createExplosion(WorldServer.java:1582) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.World.createExplosion(World.java:1011) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.boss.enderdragon.EntityEnderCrystal.damageEntity(EntityEnderCrystal.java:136) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.projectile.EntityWitherSkull.a(EntityWitherSkull.java:63) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.projectile.IProjectile.a(IProjectile.java:181) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.projectile.EntityWitherSkull.a(EntityWitherSkull.java:94) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.projectile.IProjectile.preOnHit(IProjectile.java:172) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.entity.projectile.EntityFireball.tick(EntityFireball.java:96) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1114) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.World.a(World.java:986) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:775) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-232]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
