### ISSUE TITLE
Error with Purpur since Airplane has been added

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#309]
### Minecraft's Version

1.17.1 Purpur dev 1375

### Plugin's Version

Wildstacker b198 AND b205

### Describe the bug

[01:43:11 ERROR]: Could not pass event InventoryPickupItemEvent to WildStacker v3.6.0-DEVb198
java.lang.IllegalArgumentException: size is too large
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.17.1.jar:git-Purpur-1375]
        at gg.airplane.structs.ItemListWithBitset.<init>(ItemListWithBitset.java:40) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.entity.TileEntityChest.load(TileEntityChest.java:137) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.copyData(CraftBlockEntityState.java:93) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.applyTo(CraftBlockEntityState.java:131) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftContainer.applyTo(CraftContainer.java:61) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftLootable.applyTo(CraftLootable.java:25) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftLootable.applyTo(CraftLootable.java:13) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.update(CraftBlockEntityState.java:147) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.update(CraftBlockState.java:193) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.update(CraftBlockState.java:188) ~[patched_1.17.1.jar:git-Purpur-1375]
        at com.bgsoftware.wildstacker.listeners.ItemsListener.onInventoryPickup(ItemsListener.java:246) ~[WildStacker-b198.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1467.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1375]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:561) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:503) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.entity.TileEntityHopper.lambda$pushItemsTick$0(TileEntityHopper.java:159) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:181) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.entity.TileEntityHopper.a(TileEntityHopper.java:158) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:1478) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.chunk.Chunk$c.a(Chunk.java:1430) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.World.tickBlockEntities(World.java:1106) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:821) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1635) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1375]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

Literally is just spamming console, I assume based off item pickup. Size too large seems related to possible airplane only settings but hard for me to confirm!

### Additional Information

None available.

**Comment by OmerBenGera** [comment]
The following code causes it:
```
StackedItem stackedItem = WStackedItem.of(e.getItem());
if (stackedItem.getStackAmount() > 1) {
    e.setCancelled(true);
    stackedItem.giveItemStack(e.getInventory());
    Block hopper = e.getItem().getLocation().subtract(0, 1, 0).getBlock();
    hopper.getState().update();
}
```
WildStacker adds items to the inventory of hopper, then it updates the hopper.
I don't know why Airplane things it's a chest or why this error occurs, however it's not related to WildStacker.
I recommend checking if it happens on Paper, and if it doesn't contact the developers of Airplane regarding this.

**Comment by OmerBenGera** [comment]
Try latest dev build before tho, I fixed an issue with detection of the hopper, so it might fix the issue as well.

**Comment by Skizzles** [comment]
@OmerBenGera This seems to be caused by Airplane at which I am trying to reach the dev to get resolved. I will close this out once its resolved as others who use airplane or forks containing it will experience the same issue.

**Comment by OmerBenGera** [comment]
Have you tried latest dev build?
I might have fixed it on my side..

**Comment by Skizzles** [comment]
> Have you tried latest dev build?
> I might have fixed it on my side..

Yes I did

**Comment by PaulBGD** [comment]
I'm looking into this, I'm not quite sure why it's happening. It seems that the block state that's being updated has an inventory size bigger than 64 (which is bigger than even a double chest..) Is there maybe some kind of fake block entity being created, or a custom NBT tag being loaded?

**Comment by Skizzles** [comment]
> I'm looking into this, I'm not quite sure why it's happening. It seems that the block state that's being updated has an inventory size bigger than 64 (which is bigger than even a double chest..) Is there maybe some kind of fake block entity being created, or a custom NBT tag being loaded?

Ah could be a custom chest from:
https://github.com/BG-Software-LLC/WildChests
These allow multiple pages and even slots going above 64 limit.

**Comment by OmerBenGera** [comment]
> 
> 
> > I'm looking into this, I'm not quite sure why it's happening. It seems that the block state that's being updated has an inventory size bigger than 64 (which is bigger than even a double chest..) Is there maybe some kind of fake block entity being created, or a custom NBT tag being loaded?
> 
> Ah could be a custom chest from:
> https://github.com/BG-Software-LLC/WildChests
> These allow multiple pages and even slots going above 64 limit.

They don't change behavior of vanilla chests.

**Comment by OmerBenGera** [comment]
> 
> 
> > Have you tried latest dev build?
> > I might have fixed it on my side..
> 
> Yes I did

Has it occurred after that?
As the main issue on my side was that it updated a TileEntityChest instead of TileEntityHopper and it should be fixed using this version.
