### ISSUE TITLE
Wildstacker Error

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#316]
### Minecraft's Version

1.17.1 purpur dev 1375

### Plugin's Version

dev build 209

### Describe the bug

Located some frozen mobs that would not die. After trying to kill them I did /butcher which they disappeared. This error showed after that.

### To Reproduce

Unsure on this error is below.

https://screenshots.skizzles.me/wAnA3/gejIfISa98.mp4

### Additional Information

[02:43:06 ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.6.0-DEVb209
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.syncher.DataWatcher$Item.b()" because the return value of "net.minecraft.network.syncher.DataWatcher.b(net.minecraft.network.syncher.DataWatcherObject)" is null
        at net.minecraft.network.syncher.DataWatcher.get(DataWatcher.java:135) ~[patched_1.17.1.jar:git-Purpur-1375]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.getTurtleHome(NMSAdapter_v1_17_R1.java:461) ~[WildStacker-b209.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntitySpawn(EntitiesListener.java:718) ~[WildStacker-b209.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawn(EntitiesListener.java:274) ~[WildStacker-b209.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor802.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1375]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:737) ~[patched_1.17.1.jar:git-Purpur-1375]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:642) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.WorldServer.addEntity0(WorldServer.java:1477) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1389) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.BlockTurtleEgg.tick(BlockTurtleEgg.java:135) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.world.level.block.state.BlockBase$BlockData.b(BlockBase.java:923) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:999) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1049) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:934) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1635) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1375]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1375]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed.

**Comment by Skizzles** [comment]
Seems resolved
