### ISSUE TITLE
error with wildstacker

### ISSUE THREAD

**Issue by TizoCraft** [BG-Software-LLC/WildStacker#332]
### Minecraft's Version

patched_1.17.1.jar:git-Purpur-1374

### Plugin's Version

WildStacker v3.6.0-DEVb141

### Describe the bug

error in console dont know whats causing this

### To Reproduce

idk

### Additional Information

[14:44:35 ERROR]: Could not pass event PlayerInteractEntityEvent to WildStacker v3.6.0-DEVb141
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.animal.EntityAnimal.n(net.minecraft.world.item.ItemStack)'
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.isAnimalFood(NMSAdapter_v1_17_R1.java:236) ~[WildStacker-3.6.0.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityFeed(EntitiesListener.java:716) ~[WildStacker-3.6.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1374]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1374]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1374]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2481) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2533) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2473) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1374]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
Try updating WildStacker, let me know if it fixes the issue

**Comment by TizoCraft** [comment]
but still having a problem that entitys wont move like the AI of them is disabled but nerfed mobs is disabled in config
