### ISSUE TITLE
[Bug] Error spam in console

### ISSUE THREAD

**Issue by Drc-DEV** [BG-Software-LLC/WildStacker#341]
### Minecraft's Version

1.17.1 Paper Build 302

### Plugin's Version

WildStacker v3.6.0-DEVb217

### Describe the bug

```
Could not pass event PreSpawnerSpawnEvent to WildStacker v3.6.0-DEVb217
java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.<init>(org.bukkit.block.Block, java.lang.Class)'
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1$SyncedCreatureSpawnerImpl.<init>(NMSAdapter_v1_17_R1.java:1158) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.createSyncedSpawner(NMSAdapter_v1_17_R1.java:567) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.utils.spawners.SyncedCreatureSpawner.of(SyncedCreatureSpawner.java:13) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:47) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:43) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:252) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:241) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:60) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:55) ~[WildStacker-b217.jar:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener$PaperSpawnersListener.onPreSpawnSpawner(SpawnersListener.java:734) ~[WildStacker-b217.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-302]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-302]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-302]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:626) ~[patched_1.17.1.jar:git-Paper-302]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.17.1.jar:git-Paper-302]
        at net.minecraft.world.level.BaseSpawner.serverTick(BaseSpawner.java:147) ~[app:?]
        at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:56) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1459) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1411) ~[app:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:972) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:783) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-302]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-302]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-302]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
        ```

### To Reproduce

Have some spawners in the world, the error gets spammed in console.

**Comment by Regerta** [comment]
Same here, i'am using Purpur and the error doesn't appear on Purpur Build 1400
I hope this can be fixed as soon as possible

**Comment by clownmeister** [comment]
Hello, not trying to spam. Just wanted to confirm that devs understand that this is a gamebreaking bug. Spawners dont stack and if you place them they change to pig spawners. If you try to mine them with silktouch it is not possible. So basicaly no spawner feature works at the moment. Could we possibly get some hotfix pretty please. It is not simple console spam.

**Comment by OmerBenGera** [comment]
> Hello, not trying to spam. Just wanted to confirm that devs understand that this is a gamebreaking bug. Spawners dont stack and if you place them they change to pig spawners. If you try to mine them with silktouch it is not possible. So basicaly no spawner feature works at the moment. Could we possibly get some hotfix pretty please. It is not simple console spam.

You can use another spigot jar for now, or make a pull request - I am not at home and I cant fix it right now.

**Comment by clownmeister** [comment]
Okey understandable, will try to find some working paper version that does not break everything else.
