### ISSUE TITLE
Could not pass event PreSpawnerSpawnEvent to WildStacker v3.6.1.234

### ISSUE THREAD

**Issue by iLemon** [BG-Software-LLC/WildStacker#373]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/18317307/141658557-6e8ee5db-4805-4f83-ba08-cfc592c2730e.png)

### Plugin's Version

v3.6.1.234

### Describe the bug

The following bug is spamming my console several times per second:

```
[20:45:11 ERROR]: Could not pass event PreSpawnerSpawnEvent to WildStacker v3.6.1.234
java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.<init>(org.bukkit.World, net.minecraft.world.level.block.entity.TileEntity)'
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1$SyncedCreatureSpawnerImpl.<init>(NMSAdapter_v1_17_R1.java:1173) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.createSyncedSpawner(NMSAdapter_v1_17_R1.java:578) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.utils.spawners.SyncedCreatureSpawner.of(SyncedCreatureSpawner.java:13) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:47) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:43) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:252) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:241) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:60) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:55) ~[WildStacker-3.6.1-b234.jar:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener$PaperSpawnersListener.onPreSpawnSpawner(SpawnersListener.java:734) ~[WildStacker-3.6.1-b234.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.world.level.MobSpawnerAbstract.a(MobSpawnerAbstract.java:148) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.world.level.block.entity.TileEntityMobSpawner.b(TileEntityMobSpawner.java:56) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:1478) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.world.level.chunk.Chunk$c.a(Chunk.java:1430) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.world.level.World.tickBlockEntities(World.java:1165) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:822) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1617) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1469) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[citrus-1.17.1-reobf.jar:git-Citrus-"35576b1"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### To Reproduce

Has happened every since updating to 3.6.1, and then I tried the latest dev build 234 but still get the same problem.

**Comment by OmerBenGera** [comment]
Use latest build of Paper.
If your fork doesnt support it yet, use another fork.
