### ISSUE TITLE
No enum constant com.bgsoftware.wildstacker.utils.ServerVersion.v1_18

### ISSUE THREAD

**Issue by crypticfel** [BG-Software-LLC/WildStacker#388]
### Minecraft's Version

version 3332-Spigot-a5dea1c-bc14cb6 (MC: 1.18)

### Plugin's Version

WildStacker v3.6.1.237

### Describe the bug

[21:15:43] [Server thread/INFO]: [WildStacker] Loading WildStacker v3.6.1.237
[21:15:43] [Server thread/ERROR]: null initializing WildStacker v3.6.1.237 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.bgsoftware.wildstacker.WildStackerPlugin.loadNMSAdapter(WildStackerPlugin.java:202) ~[?:?]
	at com.bgsoftware.wildstacker.WildStackerPlugin.onLoad(WildStackerPlugin.java:82) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:993) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant com.bgsoftware.wildstacker.utils.ServerVersion.v1_18
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.bgsoftware.wildstacker.utils.ServerVersion.valueOf(ServerVersion.java:5) ~[?:?]
	at com.bgsoftware.wildstacker.utils.ServerVersion.<clinit>(ServerVersion.java:26) ~[?:?]
	... 7 more

### To Reproduce

Run in Spigot 1.18

**Comment by OmerBenGera** [comment]
WildStacker doesnt aupport 1.18 as of now.
