### ISSUE TITLE
Can't use on purpur 1.18

### ISSUE THREAD

**Issue by IncludivicS** [BG-Software-LLC/WildStacker#392]
### Minecraft's Version

purpur-1.18.1-1434

### Plugin's Version

WildStacker-3.6.1-b239

### Describe the bug

can't run the plugin this is log.

[20:25:13] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:25:13] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit
[20:25:14] [Worker-Main-1/INFO]: Loaded 7 recipes
[20:25:15] [Server thread/INFO]: Starting minecraft server version 1.18.1
[20:25:15] [Server thread/INFO]: Loading properties
[20:25:15] [Server thread/INFO]: This server is running Purpur version git-Purpur-1434 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1fd37bd on HEAD)
[20:25:15] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:25:15] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:25:15] [Server thread/INFO]: Default game type: SURVIVAL
[20:25:15] [Server thread/INFO]: Generating keypair
[20:25:15] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:25:15] [Server thread/INFO]: Using default channel type
[20:25:15] [Server thread/INFO]: Paper: Using Java 11 compression from Velocity.
[20:25:15] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[20:25:16] [Server thread/ERROR]: (org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy:259) Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[20:25:20] [Server thread/WARN]: Legacy plugin CustomJoinMessages v16.0.2 does not specify an api-version.
[20:25:20] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v14.1.10
[20:25:20] [Server thread/INFO]: [BetterConcrete] Loading BetterConcrete v1.7.2
[20:25:20] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.10.10
[20:25:20] [Server thread/INFO]: [UltimateTimber] Loading UltimateTimber v2.3.0
[20:25:20] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[20:25:20] [Server thread/INFO]: [UltraPermissions] Loading UltraPermissions v5.1.6
[20:25:20] [Server thread/INFO]: [ChestSort] Loading ChestSort v12.1.3
[20:25:20] [Server thread/INFO]: [WildStacker] Loading WildStacker v3.6.1.239
[20:25:20] [Server thread/INFO]: [BetterFarming] Loading BetterFarming v4.2.6
[20:25:20] [Server thread/INFO]: [AnimatedScoreboard] Loading AnimatedScoreboard v0.2.5
[20:25:20] [Server thread/INFO]: [Essentials] Loading Essentials v2.19.1-dev+54-dae5194
[20:25:20] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.19.1-dev+54-dae5194
[20:25:20] [Server thread/INFO]: [CustomJoinMessages] Loading CustomJoinMessages v16.0.2
[20:25:20] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.19.1-dev+54-dae5194
[20:25:20] [Server thread/INFO]: [TabList] Loading TabList v5.6.0
[20:25:20] [Server thread/INFO]: [EssentialsDiscord] Loading EssentialsDiscord v2.19.1-dev+54-dae5194
[20:25:20] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:25:20] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[20:25:20] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.1-dev+54-dae5194 which is not a depend, softdepend or loadbefore of this plugin.
[20:25:20] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[20:25:20] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[20:25:20] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[20:25:20] [Server thread/INFO]: [UltraPermissions] Enabling UltraPermissions v5.1.6
[20:25:21] [Server thread/INFO]: [UltraPermissions] Loading Plugin...
[20:25:22] [Server thread/INFO]: [UltraPermissions] Hooked into Vault
[20:25:22] [Server thread/INFO]: [UltraPermissions] Successfully loaded in 1005 ms
[20:25:22] [Server thread/INFO]: Preparing level "world"
[20:25:23] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:25:23] [Server thread/INFO]: Time elapsed: 169 ms
[20:25:23] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[20:25:23] [Server thread/INFO]: Time elapsed: 117 ms
[20:25:23] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[20:25:23] [Server thread/INFO]: Time elapsed: 60 ms
[20:25:23] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.1.10
[20:25:23] [Server thread/INFO]: [SkinsRestorer] Using PaperSkinRefresher
[20:25:23] [Server thread/INFO]: [SkinsRestorer] Detected Minecraft v1_18_R1, using PaperSkinRefresher.
[20:25:23] [Server thread/INFO]: [SkinsRestorer] [ACF] Enabled Asynchronous Tab Completion Support!
[20:25:28] [Server thread/INFO]: [BetterConcrete] Enabling BetterConcrete v1.7.2
[20:25:28] [Server thread/INFO]: [BetterConcrete] This plugin was made by alex_qp
[20:25:28] [Server thread/INFO]: [BetterConcrete] furnace recipes concrete_to_powder were enabled in config.
[20:25:28] [Server thread/INFO]: [BetterConcrete] furnace recipes powder_to_glass were enabled in config.
[20:25:28] [Server thread/INFO]: [BetterConcrete] cauldron mechanic was enabled in config.
[20:25:28] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.10.10
[20:25:28] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[20:25:28] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: uperms
[20:25:28] [Server thread/INFO]: [UltraPermissions] Hooked into PlaceholderAPI
[20:25:28] [Server thread/INFO]: [UltimateTimber] Enabling UltimateTimber v2.3.0
[20:25:28] [Server thread/INFO]:  
[20:25:28] [Server thread/INFO]: =============================
[20:25:28] [Server thread/INFO]: UltimateTimber 2.3.0 by Songoda <3!
[20:25:28] [Server thread/INFO]: Action: Enabling...
[20:25:28] [Server thread/INFO]: [UltimateTimber] Loaded locale "en_US"
[20:25:28] [Server thread/INFO]: [SongodaCore] [SongodaCore] Hooked UltimateTimber.
[20:25:28] [Server thread/INFO]: =============================
[20:25:28] [Server thread/INFO]:  
[20:25:28] [Server thread/INFO]: [ChestSort] Enabling ChestSort v12.1.3
[20:25:28] [Server thread/INFO]: [ChestSort] Use permissions: false
[20:25:28] [Server thread/INFO]: [ChestSort] Current sorting method: {category},{itemsFirst},{name},{color},{customName}
[20:25:28] [Server thread/INFO]: [ChestSort] Allow automatic chest sorting:true
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Chest sorting enabled by default: false
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Sort time: close
[20:25:28] [Server thread/INFO]: [ChestSort] Allow automatic inventory sorting:true
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Inventory sorting enabled by default: false
[20:25:28] [Server thread/INFO]: [ChestSort] Auto generate category files: true
[20:25:28] [Server thread/INFO]: [ChestSort] Allow hotkeys: true
[20:25:28] [Server thread/INFO]: [ChestSort] Hotkeys enabled by default:
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Middle-Click: true
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Shift-Click: false
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Double-Click: false
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Shift-Right-Click: false
[20:25:28] [Server thread/INFO]: [ChestSort] Allow additional hotkeys: true
[20:25:28] [Server thread/INFO]: [ChestSort] Additional hotkeys enabled by default:
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Left-Click: false
[20:25:28] [Server thread/INFO]: [ChestSort]   |- Right-Click: false
[20:25:28] [Server thread/INFO]: [ChestSort] Check for updates: true
[20:25:28] [Server thread/INFO]: [ChestSort] Check interval: 4 hours (4.0 seconds)
[20:25:28] [Server thread/INFO]: [ChestSort] Categories: 900-weapons (6), 905-common-tools (4), 907-other-tools (6), 909-food (33), 910-valuables (47), 920-armor-and-arrows (9), 930-brewing (18), 950-redstone (23), 960-wood (60), 970-stone (38), 980-plants (50), 981-corals (1)
[20:25:28] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: chestsort
[20:25:28] [Server thread/INFO]: [WildStacker] Enabling WildStacker v3.6.1.239
[20:25:28] [Server thread/INFO]: [WildStacker] ******** ENABLE START ********
[20:25:28] [Server thread/INFO]: [WildStacker] Loading configuration started...
[20:25:28] [Server thread/ERROR]: Error occurred while enabling WildStacker v3.6.1.239 (Is it up to date?)
java.lang.UnsupportedOperationException: Not supported in 1.17.
	at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_18_R1.registerSpawnConditions(NMSSpawners_v1_18_R1.java:15) ~[WildStacker-3.6.1-b239.jar:?]
	at com.bgsoftware.wildstacker.handlers.SettingsHandler.<init>(SettingsHandler.java:384) ~[WildStacker-3.6.1-b239.jar:?]
	at com.bgsoftware.wildstacker.WildStackerPlugin.onEnable(WildStackerPlugin.java:145) ~[WildStacker-3.6.1-b239.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:25:28] [Server thread/INFO]: [WildStacker] Disabling WildStacker v3.6.1.239
[20:25:28] [Server thread/INFO]: [WildStacker] Cancelling tasks...
[20:25:28] [Server thread/INFO]: [WildStacker] Shutting down stacking service...
[20:25:28] [Server thread/INFO]: [WildStacker] Performing entity&items save
[20:25:28] [Server thread/INFO]: [WildStacker] Shutting down database executor
[20:25:28] [Server thread/INFO]: [WildStacker] Clearing database...
[20:25:28] [Server thread/ERROR]: Error occurred while disabling WildStacker v3.6.1.239 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.close()" because "com.bgsoftware.wildstacker.database.SQLHelper.conn" is null
	at com.bgsoftware.wildstacker.database.SQLHelper.close(SQLHelper.java:120) ~[WildStacker-3.6.1-b239.jar:?]
	at com.bgsoftware.wildstacker.handlers.DataHandler.clearDatabase(DataHandler.java:86) ~[WildStacker-3.6.1-b239.jar:?]
	at com.bgsoftware.wildstacker.WildStackerPlugin.onDisable(WildStackerPlugin.java:121) ~[WildStacker-3.6.1-b239.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1434]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:25:28] [Server thread/INFO]: [BetterFarming] Enabling BetterFarming v4.2.6
[20:25:28] [Server thread/INFO]: [BetterFarming] Version: 4.2.6 Previous: 4.2.6
[20:25:28] [Server thread/INFO]: [BetterFarming] Server: 1.18.x running Paper
[20:25:28] [Server thread/INFO]: [BetterFarming] Licensed to: 834787
[20:25:28] [Server thread/INFO]: [BetterFarming] Experiencing issues or having questions? Join our Discord!
[20:25:28] [Server thread/INFO]: [BetterFarming] Discord: https://discord.gg/B4MAJVk
[20:25:28] [Server thread/INFO]: [BetterFarming] Wiki: https://github.com/Angeschossen/BetterFarming/wiki
[20:25:28] [Server thread/INFO]: [BetterFarming]  
[20:25:28] [Server thread/INFO]: [BetterFarming] Using MySQL as database driver.
[20:25:28] [Server thread/INFO]: [BetterFarming] Successful connected to SQL database.
[20:25:29] [Server thread/INFO]: [BetterFarming] Database is ready.
[20:25:29] [Server thread/INFO]: [AnimatedScoreboard] Enabling AnimatedScoreboard v0.2.5
[20:25:29] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: animatedscoreboard
[20:25:29] [Server thread/INFO]: [Essentials] Enabling Essentials v2.19.1-dev+54-dae5194
[20:25:29] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[20:25:29] [Server thread/INFO]: [Essentials] No kits found to migrate.
[20:25:29] [Server thread/INFO]: [Essentials] Loaded 36926 items from items.json.
[20:25:29] [Server thread/INFO]: [Essentials] Using locale en_US
[20:25:29] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[20:25:29] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[20:25:29] [Server thread/INFO]: [Vault] [Economy] Essentials Economy hooked.
[20:25:29] [Server thread/INFO]: [Essentials] Using Vault based permissions (generic)
[20:25:29] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.19.1-dev+54-dae5194
[20:25:29] [Server thread/INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[20:25:29] [Server thread/INFO]: [CustomJoinMessages] Enabling CustomJoinMessages v16.0.2*
[20:25:29] [Server thread/INFO]:  _____    _______   _________ 
[20:25:29] [Server thread/INFO]: |  ___|  |_______| |  _   _  |
[20:25:29] [Server thread/INFO]: | |         | |    | | | | | |
[20:25:29] [Server thread/INFO]: | |         | |    | | | | | |
[20:25:29] [Server thread/INFO]: | |___    __| |    | | |_| | |
[20:25:29] [Server thread/INFO]: |_____|  |____|    |_|     |_|
[20:25:29] [Server thread/INFO]: by Insprill
[20:25:29] [Server thread/INFO]: PlaceholderAPI Hooked.
[20:25:29] [Server thread/INFO]: Vault Hooked.
[20:25:29] [Server thread/INFO]: Custom Join Messages has successfully started! Total time taken: 26 ms
[20:25:29] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.19.1-dev+54-dae5194
[20:25:29] [Server thread/INFO]: [EssentialsSpawn] Starting Metrics. Opt-out using the global bStats config.
[20:25:29] [Server thread/INFO]: [TabList] Enabling TabList v5.6.0
[20:25:29] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.10.10
[20:25:29] [Server thread/INFO]: [TabList] > Enabled v5.6.0 (59ms)
[20:25:29] [Server thread/INFO]: [EssentialsDiscord] Enabling EssentialsDiscord v2.19.1-dev+54-dae5194
[20:25:29] [Server thread/INFO]: [EssentialsDiscord] Starting Metrics. Opt-out using the global bStats config.
[20:25:29] [Server thread/INFO]: [EssentialsDiscord] Attempting to login to Discord...
[20:25:30] [Server thread/INFO]: [net.essentialsx.dep.net.dv8tion.jda.api.JDA] Login Successful!
[20:25:31] [JDA MainWS-ReadThread/INFO]: [net.essentialsx.dep.net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
[20:25:31] [JDA MainWS-ReadThread/INFO]: [net.essentialsx.dep.net.dv8tion.jda.api.JDA] Finished Loading!
[20:25:31] [Server thread/INFO]: [EssentialsDiscord] Successfully logged in as Andrea Application#9582
[20:25:34] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[20:25:34] [Server thread/INFO]: Running delayed init tasks
[20:25:34] [Server thread/INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[20:25:34] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: cjm
[20:25:34] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
[20:25:34] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server
[20:25:34] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: statistic
[20:25:34] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.
[20:25:34] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: world
[20:25:34] [Server thread/INFO]: 4 placeholder hooks successfully registered!
[20:25:34] [Server thread/INFO]: Done (19.179s)! For help, type "help"
[20:25:34] [Server thread/INFO]: Timings Reset
[20:25:34] [Craft Scheduler Thread - 7 - Essentials/INFO]: [Essentials] Fetching version information...
[20:25:34] [Craft Scheduler Thread - 5 - AnimatedScoreboard/INFO]: [AnimatedScoreboard] Checking for an update!
[20:25:34] [Craft Scheduler Thread - 11 - Vault/INFO]: [Vault] Checking for Updates ... 
[20:25:34] [Craft Scheduler Thread - 5 - AnimatedScoreboard/INFO]: [AnimatedScoreboard] No new versions found for the plugin!
[20:25:34] [Craft Scheduler Thread - 11 - Vault/INFO]: [Vault] No new version available
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer] ----------------------------------------------
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     +==================+
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     |------------------|
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     |  Standalone Mode |
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     +==================+
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer] ----------------------------------------------
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     Current version: 14.1.10
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer]     This is the latest version!
[20:25:34] [Craft Scheduler Thread - 3 - SkinsRestorer/INFO]: [SkinsRestorer] ----------------------------------------------
[20:25:35] [Craft Scheduler Thread - 7 - UltraPermissions/INFO]: [UltraPermissions] Loading Permission Database...
[20:25:35] [Craft Scheduler Thread - 7 - UltraPermissions/INFO]: [UltraPermissions] - 153 Permissions extracted from .jars
[20:25:35] [Server thread/INFO]: [BetterFarming] Using default currency (diamond) for economy.
[20:25:35] [Craft Scheduler Thread - 7 - UltraPermissions/INFO]: [UltraPermissions] - 7340 Permissions downloaded from the Cloud
[20:25:39] [ForkJoinPool.commonPool-worker-2/INFO]: [BetterFarming] You're using the latest version.
[20:25:42] [Craft Scheduler Thread - 1 - UltraPermissions/INFO]: [UltraPermissions] Translations successfully loaded & applied
[20:26:28] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:26:28] [Server thread/INFO]: Plugins (16): AnimatedScoreboard, BetterConcrete, BetterFarming, ChestSort, CustomJoinMessages*, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, PlaceholderAPI, SkinsRestorer, TabList, UltimateTimber, UltraPermissions, Vault, WildStacker
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:12] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:18] [Server thread/INFO]: Unknown command. Type "/help" for help.
[20:29:20] [Server thread/INFO]: Stopping the server
[20:29:20] [Server thread/INFO]: Stopping server
[20:29:20] [Server thread/INFO]: [EssentialsDiscord] Disabling EssentialsDiscord v2.19.1-dev+54-dae5194
[20:29:20] [Server thread/INFO]: [net.essentialsx.dep.net.dv8tion.jda.internal.requests.RateLimiter] Waiting for 1 bucket(s) to finish. Average queue size of 0 requests
[20:29:21] [Server thread/INFO]: [TabList] Disabling TabList v5.6.0
[20:29:21] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.19.1-dev+54-dae5194
[20:29:21] [Server thread/INFO]: [CustomJoinMessages] Disabling CustomJoinMessages v16.0.2
[20:29:21] [Server thread/INFO]: [Custom Join Messages] Shutting down threads...
[20:29:21] [Server thread/INFO]: [Custom Join Messages] All threads successfully shutdown!
[20:29:21] [Server thread/INFO]: [Custom Join Messages] Goodbye!
[20:29:21] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat v2.19.1-dev+54-dae5194
[20:29:21] [Server thread/INFO]: [Essentials] Disabling Essentials v2.19.1-dev+54-dae5194
[20:29:21] [Server thread/INFO]: [Vault] [Economy] Essentials Economy unhooked.
[20:29:21] [Server thread/INFO]: [AnimatedScoreboard] Disabling AnimatedScoreboard v0.2.5
[20:29:21] [Server thread/INFO]: [BetterFarming] Disabling BetterFarming v4.2.6
[20:29:21] [Server thread/INFO]: [BetterFarming] Saving cached data to SQL database.
[20:29:21] [Server thread/INFO]: [BetterFarming] Saved all cached worlds to SQL database.
[20:29:21] [Server thread/INFO]: [BetterFarming] Saved all cached players to SQL database.
[20:29:21] [Server thread/INFO]: [ChestSort] Disabling ChestSort v12.1.3
[20:29:21] [Server thread/INFO]: [UltraPermissions] Disabling UltraPermissions v5.1.6
[20:29:21] [Server thread/INFO]: [Vault] Disabling Vault v1.7.3-b131
[20:29:21] [Server thread/INFO]: [UltimateTimber] Disabling UltimateTimber v2.3.0
[20:29:21] [Server thread/INFO]:  
[20:29:21] [Server thread/INFO]: =============================
[20:29:21] [Server thread/INFO]: UltimateTimber 2.3.0 by Songoda <3!
[20:29:21] [Server thread/INFO]: Action: Disabling...
[20:29:21] [Server thread/INFO]: =============================
[20:29:21] [Server thread/INFO]:  
[20:29:21] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.10
[20:29:21] [Server thread/INFO]: [BetterConcrete] Disabling BetterConcrete v1.7.2
[20:29:21] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v14.1.10
[20:29:21] [Server thread/INFO]: Saving players
[20:29:21] [Server thread/INFO]: Saving worlds
[20:29:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20:29:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[20:29:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[20:29:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[20:29:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:29:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:29:23] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[20:29:25] [Server thread/INFO]: Flushing Chunk IO
[20:29:25] [Server thread/INFO]: Closing Thread Pool

### To Reproduce

Run the server

**Comment by IncludivicS** [comment]
i tested on paper1.18 too.
It same.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by IncludivicS** [comment]
Impressive!
