### ISSUE TITLE
Vindicators become invincible when stacked

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#403]
### Minecraft's Version

1.18 Purpur dev 1444

### Plugin's Version

Wildstacker dev 242

### Describe the bug

When vindicators become stacked they become invincible, unsure if it happens with unstacked however see below.

### To Reproduce

Place a spawner, have them stack, try to keep killing them.

### Additional Information

[10:46:28 WARN]: [WildStacker] Task #6674164 for WildStacker v3.6.1.242 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.bgsoftware.common.reflection.ReflectMethod.invoke(Object, Object[])" is null
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_18_R1.attemptJoinRaid(NMSAdapter_v1_18_R1.java:773) ~[WildStacker-3.6.1-b242.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.attemptJoinRaid(DeathSimulation.java:376) ~[WildStacker-3.6.1-b242.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:211) ~[WildStacker-3.6.1-b242.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1446]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest build
