### ISSUE TITLE
FastAsyncWorldEdit causing a task to fail and throw

### ISSUE THREAD

**Issue by nurdism** [BG-Software-LLC/WildStacker#408]
### Minecraft's Version

git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)

### Plugin's Version

WildStacker v3.6.2.256

### Describe the bug

Start server with [`FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-x`](https://ci.athion.net/view/%20%20FastAsyncWorldEdit/job/FastAsyncWorldEdit/) installed and this error is thrown:

```
[WildStacker] Task #120 for WildStacker v3.6.2.256 generated an exception
java.lang.NoClassDefFoundError: com/boydti/fawe/config/Settings
at com.bgsoftware.wildstacker.hooks.ConflictPluginFixer_FastAsyncWorldEdit.fixConflict(ConflictPluginFixer_FastAsyncWorldEdit.java:17) ~[WildStacker-3.6.2-b256.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:94) ~[WildStacker-3.6.2-b256.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-101]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-101]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.boydti.fawe.config.Settings
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 8 more
```

### To Reproduce

Install [`FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-x`](https://ci.athion.net/view/%20%20FastAsyncWorldEdit/job/FastAsyncWorldEdit/)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
