### ISSUE TITLE
Wildstacker not working

### ISSUE THREAD

**Issue by WolverStones** [BG-Software-LLC/WildStacker#422]
### Minecraft's Version

This server is running Purpur version git-Purpur-1504 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cb1a636 on HEAD)
[14:49:55 INFO]: You are running the latest version
[14:49:55 INFO]: Previous version: git-Purpur-1503 (MC: 1.18.1

### Plugin's Version

WildStacker version 3.6.2.261
[14:50:09 INFO]: Stacking drops, entities, blocks and spawners into one object!
[14:50:09 INFO]: Website: https://bg-software.com/
[14:50:09 INFO]: Author: Ome_R

### Describe the bug

WolverStone issued server command: /wildstacker:stacker
[14:48:02 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'wildstacker:stacker' in plugin WildStacker v3.6.2.261 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2368) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2179) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2160) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1440) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1504]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1504]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Use command /wildstacker

**Comment by OmerBenGera** [comment]
check why the plugin is not enabled and send me the errors you have from the startup logs.
This error tells you that the plugin is disabled, therefore you can't execute its commands...

**Comment by WolverStones** [comment]
> check why the plugin is not enabled and send me the errors you have from the startup logs.
> 
> This error tells you that the plugin is disabled, therefore you can't execute its commands...

https://pastebin.com/YeJ4JJcm

**Comment by WolverStones** [comment]
I don't know why, but there is about 98399 lines of text spam in the config.yml file

`# The title of the menu.`
and
`# Here you can configurable all features related to stacked items. `
https://i.imgur.com/jmhsnD0.png

**Comment by WolverStones** [comment]
so I restarted the config file and the plugin is already working

**Comment by OmerBenGera** [comment]
I will look into it.

**Comment by OmerBenGera** [comment]
This turns to be an issue with Purpur/Paper and should be fixed on latest builds of the jars.
