### ISSUE TITLE
Couldn't register a custom island-flag into SuperiorSkyblock

### ISSUE THREAD

**Issue by Ammorack** [BG-Software-LLC/WildStacker#438]
### Minecraft's Version

purpur-1.17.1-1428.jar
Server version 1.17.1

### Plugin's Version

WildStacker version 3.6.2.266

### Describe the bug

```
[04:01:30] [Server thread/INFO]: [WildStacker] Loading providers started...
[04:01:30] [Server thread/INFO]: [WildStacker]  - Couldn't find any spawners providers, using default one.
[04:01:30] [Server thread/INFO]: [WildStacker] Using Vault as an economy provider.
[04:01:30] [Server thread/INFO]: [ShopGUIPlus] Registered spawners support for WildStacker.
[04:01:30] [Server thread/INFO]: [WildStacker] Found ShopGUIPlus - Hooked as SpawnerProvider!
[04:01:30] [Server thread/INFO]: [WildStacker] Couldn't register a custom island-flag into SuperiorSkyblock - open an issue on github.
[04:01:30] [Server thread/WARN]: [WildStacker] Task #914 for WildStacker v3.6.2.266 generated an exception
java.lang.NoClassDefFoundError: com.boydti.fawe.config.Settings
	at com.bgsoftware.wildstacker.hooks.ConflictPluginFixer_FastAsyncWorldEdit.fixConflict(ConflictPluginFixer_FastAsyncWorldEdit.java:17) ~[WildStacker-3.6.2-b266.jar:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler$$Lambda$8731/0x00000000c68f4238.accept(Unknown Source) ~[WildStacker-3.6.2-b266.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:95) ~[WildStacker-3.6.2-b266.jar:?]
	at com.bgsoftware.wildstacker.handlers.ProvidersHandler$$Lambda$8497/0x00000000c6194a58.run(Unknown Source) ~[WildStacker-3.6.2-b266.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer$$Lambda$3701/0x00000000c61843f8.run(Unknown Source) ~[app:?]
	at java.lang.Thread.run(Thread.java:883) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.boydti.fawe.config.Settings
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
	... 11 more
	```

### To Reproduce

Do not know

**Comment by OmerBenGera** [comment]
I see errors about FAWE. If you remove it / use an older version, does the register warning still occurs?

**Comment by OmerBenGera** [comment]
The FAWE is fixed in latest dev build.
Let me know if the registration issue is fixed as well.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Ammorack** [comment]
Definetly forgot about this.


The error is not showing up in startup logs

**Comment by OmerBenGera** [comment]
Great.
If it occurs again, lmk.
