### ISSUE TITLE
CoreProtect hook is throwing errors

### ISSUE THREAD

**Issue by NotTooShabby** [BG-Software-LLC/WildStacker#440]
### Minecraft's Version

1.8-1.18 Paper

### Plugin's Version

Latest stable version
3.6.3

### Describe the bug

and other 1 [22:42:46] [Server thread/ERROR]: Could not pass event BlockBreakEvent to WildStacker v3.6.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:640) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.UnsupportedOperationException: Not supported in this Minecraft version.
    at com.bgsoftware.wildstacker.nms.NMSAdapter.getBlockData(NMSAdapter.java:206) ~[?:?]
    at com.bgsoftware.wildstacker.hooks.CoreProtectHook.recordBlockChange(CoreProtectHook.java:65) ~[?:?]
    at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyStackedBlockListeners$4(ProvidersHandler.java:484) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
    at com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyStackedBlockListeners(ProvidersHandler.java:483) ~[?:?]
    at com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyStackedBlockListeners(ProvidersHandler.java:478) ~[?:?]
    at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:107) ~[?:?]
    at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:339) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
    ... 18 more

### To Reproduce

can't mine spawner

**Comment by OmerBenGera** [comment]
What version of CoreProtect are you using?

**Comment by NotTooShabby** [comment]
Plugin is 2.10

**Comment by NotTooShabby** [comment]
> Plugin is 2.10. 0

**Comment by OmerBenGera** [comment]
> Plugin is 2.10

I guess it's paid?
If so, what is your discord? I'll open a ticket for you so you can send a copy of the file there.

**Comment by NotTooShabby** [comment]
Rampage19#4654

**Comment by OmerBenGera** [comment]
I opened a ticket for you :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
