### ISSUE TITLE
fawe hook error

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/WildStacker#443]
### Minecraft's Version

Tunity 1.16.5

### Plugin's Version

274

### Describe the bug

[14:21:15 WARN]: [WildStacker] Task #142 for WildStacker v3.6.3.274 generated an exception
java.lang.UnsupportedClassVersionError: com/bgsoftware/wildstacker/hooks/ConflictPluginFixer_FastAsyncWorldEdit2 has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.createInstance(ProvidersHandler.java:560) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.loadConflictPluginFixers(ProvidersHandler.java:298) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:90) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"d5261ad"]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

Startup

**Comment by OmerBenGera** [comment]
Version of FAWE that you use?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by YouSeeMeRunning2** [comment]
Fixed in latest
