### ISSUE TITLE
Error: Could not pass event EntityDamageByEntityEvent to WildStacker

### ISSUE THREAD

**Issue by paint2005** [BG-Software-LLC/WildStacker#445]
### Minecraft's Version

1.18.1

### Plugin's Version

Using Wild Stacker 
Dev builds #278
No other spawner plugin 

### Describe the bug

Im just getting the following error in panel 

### To Reproduce

Im not sure how to Reproduce but currently im testing the server and i have lots of active spawners and all the mobs from spawners drop from hight to die. Im using wild chest's chunk collector to collect the dropping

This is the Error im getting in panel. 
`[00:31:14 ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v3.6.3.278
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.trading.MerchantRecipeList.a()" because the return value of "com.bgsoftware.common.reflection.ReflectField.get(Object)" is null
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_18_R1.spawnZombieVillager(NMSAdapter_v1_18_R1.java:236) ~[WildStacker-3.6.3-b278.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.checkForZombieVillager(DeathSimulation.java:288) ~[WildStacker-3.6.3-b278.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:95) ~[WildStacker-3.6.3-b278.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityLastDamage(EntitiesListener.java:238) ~[WildStacker-3.6.3-b278.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor635.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-186]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1141) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1000) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:954) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1175) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2053) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1335) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1582) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:363) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:152) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:144) ~[?:?]
        at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:152) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:143) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:857) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3255) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:628) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:268) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2905) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:396) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:238) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-186]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:31:19 ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v3.6.3.278
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.trading.MerchantRecipeList.a()" because the return value of "com.bgsoftware.common.reflection.ReflectField.get(Object)" is null
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_18_R1.spawnZombieVillager(NMSAdapter_v1_18_R1.java:236) ~[WildStacker-3.6.3-b278.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.checkForZombieVillager(DeathSimulation.java:288) ~[WildStacker-3.6.3-b278.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:95) ~[WildStacker-3.6.3-b278.jar:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityLastDamage(EntitiesListener.java:238) ~[WildStacker-3.6.3-b278.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor635.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-186]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1141) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1000) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:954) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1175) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2053) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1335) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1582) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:363) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:152) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:144) ~[?:?]
        at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:152) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:143) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:857) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3255) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:628) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:268) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2905) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:396) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:238) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-186]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Additional Information

in other testing few spawner mobs spawn on magma block and only zombies despawn immediately after spawning on a magma block. i have removed all the spawning conditions in wild stacker config with 'instant-kill: HOT_FLOOR'

**Comment by OmerBenGera** [comment]
Use latest dev build and it will be fixed.
About the other issue you mentioned, doesn't sound like an issue with the plugin - sounds like they despawn naturally.

**Comment by paint2005** [comment]
im using the latest dev build #278 i mentioned it above ?

**Comment by OmerBenGera** [comment]
What version of Paper are you using?

**Comment by paint2005** [comment]
1.18.1 build #186 latest

**Comment by paint2005** [comment]
i figured out the zombie despawn problem, its Wild Loader. they dont despawn when player is loading the spawners

**Comment by OmerBenGera** [comment]
> i figured out the zombie despawn problem, its Wild Loader. they dont despawn when player is loading the spawners

Right. WildLoaders cannot make nearby mobs to not despawn.
