### ISSUE TITLE
WildStacker failed main thread check

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#483]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b297

### Describe the bug

since i upated the plugin for  some reason some spawner are spawning enity 3 by 3 but there is 100 spawners stacked , its not hapening eveerytime and to everyone it seems to be random and i also got that stack trace on the console , the bug come since that stack trace `[13:37:58] [Craft Scheduler Thread - 2785 - WildStacker/FATAL]: Thread Craft Scheduler Thread - 2785 - WildStacker failed main thread check: Entity remove
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:607) ~[app:?]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4285) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.world.entity.Entity.remove(Entity.java:629) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at com.bgsoftware.wildstacker.nms.NMSHolograms_v1_17_R1$EntityHologram.removeHologram(NMSHolograms_v1_17_R1.java:66) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedHologramObject.removeHologram(WStackedHologramObject.java:15) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.handlers.DataHandler.removeStackedSpawner(DataHandler.java:100) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.removeStackObject(SystemHandler.java:117) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.performCacheClear(SystemHandler.java:387) ~[WildStacker-3.7.0-b297.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:37:59] [Craft Scheduler Thread - 2785 - WildStacker/WARN]: [WildStacker] Plugin WildStacker v3.7.0.297 generated an exception while executing task 138
java.lang.IllegalStateException: Asynchronous Entity remove!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:607) ~[app:?]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4285) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at net.minecraft.world.entity.Entity.remove(Entity.java:629) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at com.bgsoftware.wildstacker.nms.NMSHolograms_v1_17_R1$EntityHologram.removeHologram(NMSHolograms_v1_17_R1.java:66) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedHologramObject.removeHologram(WStackedHologramObject.java:15) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.handlers.DataHandler.removeStackedSpawner(DataHandler.java:100) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.removeStackObject(SystemHandler.java:117) ~[WildStacker-3.7.0-b297.jar:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.performCacheClear(SystemHandler.java:387) ~[WildStacker-3.7.0-b297.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### To Reproduce

instal the lastest wildstacker and wait a bit

**Comment by amarcais53** [comment]
i uploaded it there https://pastebin.com/jx4Gg9G8

**Comment by amarcais53** [comment]
rstarting the server fixes the issue but it can come again sometimes

**Comment by OmerBenGera** [comment]
> after now 8 days i didnt got the bug again so i guess it was a bad luck ?

Might have been.
I will fix it on my side tho, don't worry.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.

**Comment by amarcais53** [comment]
thank you
