### ISSUE TITLE
SuperiorSkyblock hook not working

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildStacker#490]
### Minecraft's Version

  [Mon 20:26:16 INFO ] Current: git-Purpur-1586 (MC: 1.18.2)*

### Plugin's Version

  [Mon 20:27:19 INFO ] WildStacker version 3.7.0
  [Mon 20:27:19 INFO ] Stacking drops, entities, blocks and spawners into one object!
  [Mon 20:27:19 INFO ] Website: https://bg-software.com/
  [Mon 20:27:19 INFO ] Author: Ome_R

### Describe the bug

I have SuperiorSkyblock hook set to true in config for wildstacker, and have correctly added it to settings.yml, but gives me this error when reloading plugin/restarting server: https://pastebin.com/ATGiK9R1

### To Reproduce

Add menu item to settings.yml

### Additional Information

![C429D932-7878-458C-849D-CE267DFC309E](https://user-images.githubusercontent.com/65089425/161661528-be2d01fd-cb5e-4d24-ae94-58fdcb24521a.png)
![93AE4673-7A07-4404-990B-94947F951B34](https://user-images.githubusercontent.com/65089425/161661530-be9265e7-f3bd-464c-9224-d480fa3b0625.png)

**Comment by OmerBenGera** [comment]
It seems to work fine for me
Mind sending me your settings menu file?

**Comment by DuneSciFye** [comment]
https://pastebin.com/B8jpTKLW there it is

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build of **SuperiorSkyblock**; let me know if it works for you.

**Comment by DuneSciFye** [comment]
DuneSciFye issued server command: /is settings

Console
12:05:52

java.lang.NullPointerException: settings parameter cannot be null.
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.island.SIsland.hasSettingsEnabled(SIsland.java:2762)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.button.impl.menu.IslandFlagPagedObjectButton.modifyButtonItem(IslandFlagPagedObjectButton.java:33)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.button.impl.menu.IslandFlagPagedObjectButton.modifyButtonItem(IslandFlagPagedObjectButton.java:18)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.button.PagedObjectButton.getButtonItem(PagedObjectButton.java:45)

INFO
12:05:52

[SuperiorSkyblock2]: Failed to load menu because due to an error with slot #11

Console
12:05:52

at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.pattern.impl.PagedMenuPattern.setupInventory(PagedMenuPattern.java:63)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.pattern.impl.PagedMenuPattern.setupInventory(PagedMenuPattern.java:21)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.pattern.SuperiorMenuPattern.buildInventory(SuperiorMenuPattern.java:80)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.SuperiorMenu.getInventory(SuperiorMenu.java:151)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.SuperiorMenu.open(SuperiorMenu.java:306)
at SuperiorSkyblock2-1.10.0-b641.jar//com.bgsoftware.superiorskyblock.menu.SuperiorMenu.lambda$open$6(SuperiorMenu.java:278)
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by DuneSciFye** [comment]
![image](https://user-images.githubusercontent.com/65089425/167262481-1a7de9bf-fd61-474d-b27f-98d5772ff9b8.png)
A zombie head should be after the wither skull

**Comment by OmerBenGera** [comment]
@DuneSciFye Upload entire session logs to pastebin and send it here

**Comment by DuneSciFye** [comment]
https://paste.helpch.at/icajuyecat.md

**Comment by OmerBenGera** [comment]
Does this still happen in v1.10.1 of SSB?

**Comment by DuneSciFye** [comment]
Testing now

**Comment by DuneSciFye** [comment]
![image](https://user-images.githubusercontent.com/65089425/169661404-8f3a5bc2-26d1-4125-a115-9e8c6b5091e1.png)

**Comment by DuneSciFye** [comment]
https://pastebin.com/AV6WsyUj
Heres my file. I restarted the server as well

**Comment by OmerBenGera** [comment]
> https://pastebin.com/AV6WsyUj Heres my file. I restarted the server as well

Send me logs again.

**Comment by OmerBenGera** [comment]
Check out v1.10.1.663 of SSB, hopefully it will work
