### ISSUE TITLE
1.19 Experimental Builds 

### ISSUE THREAD

**Issue by OmerBenGera** [BG-Software-LLC/WildStacker#520]
This issue is a global issue to report bugs related to the 1.19 experimental builds.

You can find the experimental builds on https://hub.bg-software.com/job/1.19%20Experimental%20Builds/

**Comment by IncludivicS** [comment]
I cant use command /ws give it error.
Wildstacker 3.7.0-b1 w/ spigot1.19.jar


[19:56:13] [Server thread/INFO]: Keizenbergz_ issued server command: /ws give Keizenbergz_ egg allay 900
[19:56:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ws' in plugin WildStacker v3.7.0.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.a(String, net.minecraft.nbt.NBTBase)" because "nbtTagCompound" is null
at com.bgsoftware.wildstacker.nms.NMSMappings_v1_19_R1.put(NMSMappings_v1_19_R1.java:460) ~[?:?]
at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.setTag(NMSAdapter_v1_19_R1.java:998) ~[?:?]
at com.bgsoftware.wildstacker.utils.items.ItemUtils.setSpawnerItemAmount(ItemUtils.java:111) ~[?:?]
at com.bgsoftware.wildstacker.command.commands.CommandGive.perform(CommandGive.java:127) ~[?:?]
at com.bgsoftware.wildstacker.command.CommandsHandler.onCommand(CommandsHandler.java:54) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
... 20 more

**Comment by OmerBenGera** [comment]
> I cant use command /ws give it error. Wildstacker 3.7.0-b1 w/ spigot1.19.jar
> 
> [19:56:13] [Server thread/INFO]: Keizenbergz_ issued server command: /ws give Keizenbergz_ egg allay 900 [19:56:13] [Server thread/ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'ws' in plugin WildStacker v3.7.0.1 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36] at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.a(String, net.minecraft.nbt.NBTBase)" because "nbtTagCompound" is null at com.bgsoftware.wildstacker.nms.NMSMappings_v1_19_R1.put(NMSMappings_v1_19_R1.java:460) ~[?:?] at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.setTag(NMSAdapter_v1_19_R1.java:998) ~[?:?] at com.bgsoftware.wildstacker.utils.items.ItemUtils.setSpawnerItemAmount(ItemUtils.java:111) ~[?:?] at com.bgsoftware.wildstacker.command.commands.CommandGive.perform(CommandGive.java:127) ~[?:?] at com.bgsoftware.wildstacker.command.CommandsHandler.onCommand(CommandsHandler.java:54) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?] ... 20 more

Fixed in latest dev build of 1.19 - build 2 :)

**Comment by IncludivicS** [comment]
did smart-breeding consume only 1 stack now? 
it consume 900 if the cows are 900 previously.

**Comment by OmerBenGera** [comment]
> Smart-breeding consume only 1 stack now. It consume 900 if the cows are 900 previously.

Not related to 1.19 - open a new issue please :)

**Comment by IncludivicS** [comment]
When chicken lay egg this happen?

[02:33:45] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to WildStacker v3.7.0.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:712) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:607) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1022) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:959) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.level.WorldServer.b(WorldServer.java:954) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.entity.Entity.a(Entity.java:2070) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.entity.Entity.a(Entity.java:2039) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.entity.Entity.a(Entity.java:2034) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.entity.animal.EntityChicken.w_(EntityChicken.java:99) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2841) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:389) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:826) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.level.World.a(World.java:658) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.level.WorldServer.lambda$9(WorldServer.java:421) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1290) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1010) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.bgsoftware.common.reflection.ReflectField.get(Object)" is null
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.getEggLayTime(NMSAdapter_v1_19_R1.java:341) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.events.EventsListener$EggLay.lambda$onEggLay$0(EventsListener.java:126) ~[?:?]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.lambda$getNearbyEntities$0(NMSAdapter_v1_19_R1.java:394) ~[?:?]
        at net.minecraft.world.level.entity.EntitySection.a(SourceFile:35) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.level.entity.EntitySectionStorage.a(SourceFile:120) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.level.entity.EntitySectionStorage.a(SourceFile:65) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.level.entity.EntitySectionStorage.b(SourceFile:120) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.world.level.entity.LevelEntityGetterAdapter.a(SourceFile:42) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.getNearbyEntities(NMSAdapter_v1_19_R1.java:393) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.EntitiesGetter.getNearbyEntities(EntitiesGetter.java:38) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.events.EventsListener$EggLay.onEggLay(EventsListener.java:125) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 25 more

**Comment by HellOnBlocks** [comment]
> When chicken lay egg this happen.
> 
> [02:33:45] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to WildStacker v3.7.0.3 org.bukkit.event.EventException: null

I am getting the same thing. But I don't see any chickens around me...
Paper version git-Paper-20 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
WildStacker Version: 3.7.0.3

**Comment by OmerBenGera** [comment]
> > When chicken lay egg this happen.
> > [02:33:45] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to WildStacker v3.7.0.3 org.bukkit.event.EventException: null
> 
> I am getting the same thing. But I don't see any chickens around me... Brand new plugin install, not using any previous configs. Paper version git-Paper-20 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) WildStacker Version: 3.7.0.3

Will look into it, dont worry.

**Comment by OmerBenGera** [comment]
@IncludivicS @HellOnBlocks Fixed.

**Comment by SrMonsterYT** [comment]
this keeps appearing randomly in the console: https://pastebin.com/7qtctbD6

**Comment by OmerBenGera** [comment]
> this keeps appearing randomly in the console: https://pastebin.com/7qtctbD6

Already fixed, update.
