### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by Gida4** [BG-Software-LLC/WildStacker#536]
### Minecraft's Version

git-Purpur-1699 (MC: 1.19)
purpur-1.19-1699.jar

### Plugin's Version

WildStacker-3.8.0-b317

### Describe the bug

[15:23:59 ERROR]: Thread dumps: 
Craft Scheduler Thread - 122 - WildStacker: 
        at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
        at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:87)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:77)
        at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
        at net.minecraft.world.level.levelgen.BitRandomSource.a(BitRandomSource.java:26)
        at net.minecraft.world.entity.animal.EntityWaterAnimal.dP(EntityWaterAnimal.java:46)
        at net.minecraft.world.entity.EntityLiving.getExpReward(EntityLiving.java:1824)
        at WildStacker.jar//com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.getEntityExp(NMSAdapter_v1_19_R1.java:304)
        at WildStacker.jar//com.bgsoftware.wildstacker.loot.LootTable.getExp(LootTable.java:151)
        at WildStacker.jar//com.bgsoftware.wildstacker.objects.WStackedEntity.getExp(WStackedEntity.java:528)
        at WildStacker.jar//com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$simulateDeath$4(DeathSimulation.java:138)
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[15:23:59 WARN]: [WildStacker] Plugin WildStacker v3.8.0.317 generated an exception while executing task 264582
net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:83) ~[purpur-1.19.jar:git-Purpur-1699]
        at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45) ~[purpur-1.19.jar:git-Purpur-1699]
        at net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:26) ~[purpur-1.19.jar:git-Purpur-1699]
        at net.minecraft.world.entity.animal.WaterAnimal.getExperienceReward(WaterAnimal.java:46) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.getExpReward(LivingEntity.java:1824) ~[?:?]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.getEntityExp(NMSAdapter_v1_19_R1.java:304) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.loot.LootTable.getExp(LootTable.java:151) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.getExp(WStackedEntity.java:528) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$simulateDeath$4(DeathSimulation.java:138) ~[WildStacker.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1699]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1699]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79) ~[purpur-1.19.jar:git-Purpur-1699]
        ... 14 more

### To Reproduce

Nothing, I see to console log.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by OmerBenGera** [comment]
Closing this for now
If it still occurs, lmk
