### ISSUE TITLE
Cannot convert PLAYER into a stacked entity.

### ISSUE THREAD

**Issue by Areanydd** [BG-Software-LLC/WildStacker#537]
### Minecraft's Version

Spigot 1.17.1

### Plugin's Version

3.8.0.316

### Describe the bug

Caused by: java.lang.IllegalArgumentException: Cannot convert PLAYER into a stacked entity.
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedEntity(SystemHandler.java:132) ~[?:?]
        at com.bgsoftware.wildstacker.api.WildStackerAPI.getStackedEntity(WildStackerAPI.java:59) ~[?:?]
        at net.devtm.tmmobcoins.util.Stackers.StackerHooks.getEntityCount(StackerHooks.java:36) ~[?:?]
        at net.devtm.tmmobcoins.listener.BasicListener.onPlayerKillEntity(BasicListener.java:63) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[SkyBlockUniverse.jar:3284a-Spigot-3892929-0ab8487]
        ... 28 more

### To Reproduce

When i kill someone, i receive an error from TMMobcoins with that error, i was thinking it s not a compatibility there or something..i don t know exactly and they don t respond me :/

**Comment by OmerBenGera** [comment]
This is an issue with net.devtm.tmmobcoins, not WildStacker. Contact them to solve the issue
