### ISSUE TITLE
EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.

### ISSUE THREAD

**Issue by Cutroo** [BG-Software-LLC/WildStacker#560]
### Minecraft's Version

WindSpigot 1.8.8

### Plugin's Version

WildStacker last version (3.8.0)

### Describe the bug

When i try to kill a mob doesn't died and in the console spam this error.

[13:41:11] [epollEventLoopGroup-3-9/ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v3.8.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[WindSpigot-2.1.2.jar:]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:168) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:670) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:574) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:707) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1217) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:793) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[WindSpigot-2.1.2.jar:]
	at eu.decentsoftware.holograms.api.nms.PacketHandler__Custom.channelRead(PacketHandler__Custom.java:18) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[WindSpigot-2.1.2.jar:]
	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.channelRead(BukkitPipelineInjector.java:60) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WindSpigot-2.1.2.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[WindSpigot-2.1.2.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WindSpigot-2.1.2.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[WindSpigot-2.1.2.jar:]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WindSpigot-2.1.2.jar:]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[WindSpigot-2.1.2.jar:]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[WindSpigot-2.1.2.jar:]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[WindSpigot-2.1.2.jar:]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[WindSpigot-2.1.2.jar:]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[WindSpigot-2.1.2.jar:]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[WindSpigot-2.1.2.jar:]
	at com.bgsoftware.wildstacker.utils.events.EventsCaller.callEntityUnstackEvent(EventsCaller.java:80) ~[?:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.runUnstack(WStackedEntity.java:305) ~[?:?]
	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:100) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityLastDamage(EntitiesListener.java:244) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot-2.1.2.jar:]
	... 57 more

### To Reproduce

.

**Comment by Jake4-CX** [comment]
The error for this is "EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.", perhaps try using PaperSpigot than some unstable multithreading branch of NachoSpigot.

**Comment by Cutroo** [comment]
There is any other solutions then change the spigot?

**Comment by Jake4-CX** [comment]
Just try using PaperSpigot (or NachoSpigot) and see if this fixes your issue, I doubt you'll need to use another fork unless the player count is in the hunrderds.

**Comment by Cutroo** [comment]
work in NachoSpigot, but i want fix in WindSpigot...

**Comment by Jake4-CX** [comment]
This **is not** a fault with this plugin, this is because of WindSpigot. I have looked at your server and it currently only has 2 players online so there is no need to use another fork of 1.8.8 PaperSpigot, it is able to support over one hundred players without breaking a sweat.

**Comment by broken1arrow** [comment]
> This **is not** a fault with this plugin, this is because of WindSpigot. I have looked at your server and it currently only has 2 players online so there is no need to use another fork of 1.8.8 PaperSpigot, it is able to support over one hundred players without breaking a sweat.

is recommended to use fork some get updates (at least some recommend use other fork an spigot or papermc for 1.8.8).

**Comment by broken1arrow** [comment]
> work in NachoSpigot, but i want fix in WindSpigot...

Do they still support 1.8.8? then ask if the dev on WindSpigot if they has some solution for this. I´m not 100% sure if Oma_r shall drop support for 1.8.8 (I know some plugins has he planed drop support for some old minecraft versions).

**Comment by OmerBenGera** [comment]
I will fix it on my side, no worries.

Also, I dont have any plans on dropping support for 1.8.8. I am currently supporting 1.8.8, 1.12 and the 3 most recently versions (1.17, 1.18, 1.19 - 1.16 support will be dropped soon)

**Comment by OmerBenGera** [comment]
Contact WindSpigot developers regarding this.
WildStacker sets the async status of the event correctly, and the event should be fired on both synchornized and asynchronized threads.
