### ISSUE TITLE
WildStacker Warns thrown on 1.19.1

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#564]
### Minecraft's Version

1.19.1 Paper build 94

### Plugin's Version

dev b323

### Describe the bug

Warn issues being spammed by wildstacker

### To Reproduce

Spawning a frog into the game threw these errors, some seem to be present and spammed in logs without a frog.

### Additional Information

[20:35:45] [Server thread/WARN]: [WildStacker] Task #47860 for WildStacker v3.8.0.323 generated an exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.animal.EntityAnimal.fQ()'
	at com.bgsoftware.wildstacker.nms.NMSMappings_v1_19_R1.isInLove(NMSMappings_v1_19_R1.java:200) ~[WildStacker-3.8.0-b323.jar:?]
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.isInLove(NMSAdapter_v1_19_R1.java:281) ~[WildStacker-3.8.0-b323.jar:?]
	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.canBeBred(EntityUtils.java:454) ~[WildStacker-3.8.0-b323.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.runStackCheck(WStackedEntity.java:236) ~[WildStacker-3.8.0-b323.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.lambda$runStackAsync$10(WStackedEntity.java:629) ~[WildStacker-3.8.0-b323.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.runStackAsync(WStackedEntity.java:630) ~[WildStacker-3.8.0-b323.jar:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$handleEntitySpawn$16(EntitiesListener.java:815) ~[WildStacker-3.8.0-b323.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-94]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:35:46] [Server thread/INFO]: ISkizzlesI issued server command: /spawnmob frogt
[20:35:47] [Server thread/WARN]: [WildStacker] Task #47865 for WildStacker v3.8.0.323 generated an exception
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.Float (java.lang.Boolean and java.lang.Float are in module java.base of loader 'bootstrap')
	at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_19_R1.playDeathSound(NMSAdapter_v1_19_R1.java:764) ~[WildStacker-3.8.0-b323.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.lambda$runUnstack$5(WStackedEntity.java:322) ~[WildStacker-3.8.0-b323.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-94]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
