### ISSUE TITLE
Upgrades Menu doesn't open / Custom mob drops doesn't work to (Or i just done it incorrectly)

### ISSUE THREAD

**Issue by Ignius14** [BG-Software-LLC/WildStacker#573]
### Minecraft's Version

1.19

### Plugin's Version

Latest

### Describe the bug

I can't open any menus for the spawner when i right clicking it. I don't really get support in 02:00. I assume its bug. 

Btw, custom mob drops doesn't work. I don't get any errors to.

### To Reproduce

I think i descripted it corecctly in [Describe the bug]

### Additional Information

Config: https://paste.helpch.at/qucizikelu.bash

Log: https://paste.helpch.at/osaxuqucuz.md (I was running server on my computer so don't worry about those erorrs below)

Lootables (Zombie json): https://paste.helpch.at/pulixexeku.json

Menus:

- Upgrades: https://paste.helpch.at/igaquxuwix.coffeescript

- Manage menu: https://paste.helpch.at/gikorijodo.coffeescript

- Amounts menu: https://paste.helpch.at/edezunanoj.bash

**Comment by OmerBenGera** [comment]
There's a formatting error with your config, check out the console output next time:
```
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/INFO]: [WildStacker] Loading configuration started...
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:  in 'reader', line 478, column 3:
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:       enabled: false
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:       ^
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: expected <block end>, but found '<block mapping start>'
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:  in 'reader', line 2723, column 5:
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:         amounts-menu: false
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:         ^
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at WildStacker-3.8.0.jar//com.bgsoftware.common.config.CommentedConfiguration.loadFromString(CommentedConfiguration.java:137)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at WildStacker-3.8.0.jar//com.bgsoftware.common.config.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:325)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at WildStacker-3.8.0.jar//com.bgsoftware.common.config.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:291)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at WildStacker-3.8.0.jar//com.bgsoftware.wildstacker.handlers.SettingsHandler.<init>(SettingsHandler.java:150)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at WildStacker-3.8.0.jar//com.bgsoftware.wildstacker.handlers.SettingsHandler.reload(SettingsHandler.java:515)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at WildStacker-3.8.0.jar//com.bgsoftware.wildstacker.command.commands.CommandReload.lambda$perform$0(CommandReload.java:53)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: Caused by: while parsing a block mapping
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:  in 'reader', line 478, column 3:
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:       enabled: false
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:       ^
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: expected <block end>, but found '<block mapping start>'
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:  in 'reader', line 2723, column 5:
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:         amounts-menu: false
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]:         ^
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102)
[01:52:25] [Craft Scheduler Thread - 270 - WildStacker/WARN]: 	... 12 more
```

Fix it and everything will work.
