### ISSUE TITLE
Wildstacker dev 328 errors

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#574]
### Minecraft's Version

1.19.1 Purpur 1748

### Plugin's Version

dev 328

### Describe the bug

On startup these errors appear.

### To Reproduce

Start the plugin on purpur 1748

### Additional Information

[06:54:08 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] class com.bgsoftware.wildstacker.nms.v1_19_R1.NMSHolograms$EntityHologram overrides final method net.minecraft.world.entity.Entity.cz()Lnet/minecraft/world/phys/AxisAlignedBB; initializing WildStacker v3.8.0.328 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class com.bgsoftware.wildstacker.nms.v1_19_R1.NMSHolograms$EntityHologram overrides final method net.minecraft.world.entity.Entity.cz()Lnet/minecraft/world/phys/AxisAlignedBB;
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:200) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:110) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.bgsoftware.wildstacker.WildStackerPlugin.loadNMSAdapter(WildStackerPlugin.java:204) ~[WildStacker-3.8.0-b328.jar:?]
        at com.bgsoftware.wildstacker.WildStackerPlugin.onLoad(WildStackerPlugin.java:85) ~[WildStacker-3.8.0-b328.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:458) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1732]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
[06:54:30 INFO]: [WildStacker] Loading configuration started...
[06:54:31 ERROR]: Error occurred while enabling WildStacker v3.8.0.328 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildstacker.nms.NMSSpawners.registerSpawnConditions()" because the return value of "com.bgsoftware.wildstacker.WildStackerPlugin.getNMSSpawners()" is null
        at com.bgsoftware.wildstacker.handlers.SettingsHandler.<init>(SettingsHandler.java:380) ~[WildStacker-3.8.0-b328.jar:?]
        at com.bgsoftware.wildstacker.WildStackerPlugin.onEnable(WildStackerPlugin.java:145) ~[WildStacker-3.8.0-b328.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:425) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1732]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:54:31 INFO]: [WildStacker] Disabling WildStacker v3.8.0.328
[06:54:31 INFO]: [WildStacker] Cancelling tasks...
[06:54:31 INFO]: [WildStacker] Shutting down stacking service...
[06:54:31 INFO]: [WildStacker] Performing entity&items save
[06:54:31 INFO]: Shutting down database executor
[06:54:31 INFO]: [WildStacker] Clearing database...
[06:54:31 ERROR]: Error occurred while disabling WildStacker v3.8.0.328 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.close()" because "com.bgsoftware.wildstacker.database.SQLHelper.conn" is null
        at com.bgsoftware.wildstacker.database.SQLHelper.close(SQLHelper.java:120) ~[WildStacker-3.8.0-b328.jar:?]
        at com.bgsoftware.wildstacker.handlers.DataHandler.clearDatabase(DataHandler.java:86) ~[WildStacker-3.8.0-b328.jar:?]
        at com.bgsoftware.wildstacker.WildStackerPlugin.onDisable(WildStackerPlugin.java:121) ~[WildStacker-3.8.0-b328.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:425) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1732]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
It works fine for me on Purpur 1749 and WildStacker 328

**Comment by Skizzles** [comment]
Seems some of these are from trying to generate fresh loot tables.

**Comment by Skizzles** [comment]
Unsure if this is related at all

[02:34:27] [Server thread/ERROR]: BlockEntity threw exception at Build_World:-1598,0,3811
java.lang.ClassCastException: class com.bgsoftware.wildstacker.nms.v1_19_R1.mappings.net.minecraft.world.level.World cannot be cast to class net.minecraft.world.level.GeneratorAccessSeed (com.bgsoftware.wildstacker.nms.v1_19_R1.mappings.net.minecraft.world.level.World is in unnamed module of loader 'WildStacker-3.8.0-b328.jar' @309f980f; net.minecraft.world.level.GeneratorAccessSeed is in unnamed module of loader java.net.URLClassLoader @52e677af)
	at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners.lambda$registerSpawnConditions$10(NMSSpawners.java:222) ~[WildStacker-3.8.0-b328.jar:?]
	at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$1.test(NMSSpawners.java:125) ~[WildStacker-3.8.0-b328.jar:?]
	at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$1.test(NMSSpawners.java:122) ~[WildStacker-3.8.0-b328.jar:?]
	at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$StackedMobSpawner.lambda$attemptMobSpawning$0(NMSSpawners.java:504) ~[WildStacker-3.8.0-b328.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$StackedMobSpawner.attemptMobSpawning(NMSSpawners.java:504) ~[WildStacker-3.8.0-b328.jar:?]
	at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$StackedMobSpawner.a(NMSSpawners.java:466) ~[WildStacker-3.8.0-b328.jar:?]
	at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:53) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1246) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1198) ~[?:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1028) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:736) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1580) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
> Unsure if this is related at all
> 
> [02:34:27] [Server thread/ERROR]: BlockEntity threw exception at Build_World:-1598,0,3811 java.lang.ClassCastException: class com.bgsoftware.wildstacker.nms.v1_19_R1.mappings.net.minecraft.world.level.World cannot be cast to class net.minecraft.world.level.GeneratorAccessSeed (com.bgsoftware.wildstacker.nms.v1_19_R1.mappings.net.minecraft.world.level.World is in unnamed module of loader 'WildStacker-3.8.0-b328.jar' @309f980f; net.minecraft.world.level.GeneratorAccessSeed is in unnamed module of loader java.net.URLClassLoader @52e677af) at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners.lambda$registerSpawnConditions$10(NMSSpawners.java:222) ~[WildStacker-3.8.0-b328.jar:?] at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$1.test(NMSSpawners.java:125) ~[WildStacker-3.8.0-b328.jar:?] at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$1.test(NMSSpawners.java:122) ~[WildStacker-3.8.0-b328.jar:?] at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$StackedMobSpawner.lambda$attemptMobSpawning$0(NMSSpawners.java:504) ~[WildStacker-3.8.0-b328.jar:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?] at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$StackedMobSpawner.attemptMobSpawning(NMSSpawners.java:504) ~[WildStacker-3.8.0-b328.jar:?] at com.bgsoftware.wildstacker.nms.v1_19_R1.NMSSpawners$StackedMobSpawner.a(NMSSpawners.java:466) ~[WildStacker-3.8.0-b328.jar:?] at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:53) ~[?:?] at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1246) ~[?:?] at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1198) ~[?:?] at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1028) ~[?:?] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:736) ~[?:?] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1580) ~[purpur-1.19.1.jar:git-Purpur-1749] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.1.jar:git-Purpur-1749] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.1.jar:git-Purpur-1749] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1749] at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1749] at java.lang.Thread.run(Thread.java:833) ~[?:?]

So the plugin is loading now...?
I don't understand anything in this report.
What's the current state of the plugin? Only throwing these errors, or it just doesn't load at all?

**Comment by Skizzles** [comment]
This seems to be loading fine after updating to 381
