### ISSUE TITLE
Spawner Dont Spawn Mobs and Mobs dont die.

### ISSUE THREAD

**Issue by realgamerk** [BG-Software-LLC/WildStacker#601]
### Minecraft's Version

Version: 1.8.8
Jar: WindSpigot

### Plugin's Version

WindSpigot 2.1.2 Release

### Describe the bug

Spawners dont Spawn Mobs, even tho its night time.
and Mobs dont die they are Immortal if i enable Entities Stacking

### To Reproduce

If i place a Spawner it wont spawn a Single or Stacked Mob.

Mobs dont die even tho it has sharpness 10

### Additional Information

Also Thing thing spams this up

[06:57:16 ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v3.8.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:168) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:670) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:574) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:707) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1217) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:793) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44) ~[server.jar:]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:]
        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.channelRead(BukkitPipelineInjector.java:59) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.IllegalStateException: EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[server.jar:]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callEntityUnstackEvent(EventsCaller.java:80) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.runUnstack(WStackedEntity.java:306) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:100) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityLastDamage(EntitiesListener.java:244) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]
        ... 67 more
[06:57:16 ERROR]: Could not pass event EntityDeathEvent to WildStacker v3.8.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:475) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:935) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:872) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44) ~[server.jar:]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:]
        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.channelRead(BukkitPipelineInjector.java:59) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.IllegalStateException: EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[server.jar:]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callEntityUnstackEvent(EventsCaller.java:80) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.runUnstack(WStackedEntity.java:306) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:100) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntityLastDamage(EntitiesListener.java:244) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onCustomEntityDeath(EntitiesListener.java:165) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]
        ... 64 more

**Comment by realgamerk** [comment]
Confirmation: The "Time until Spawn" on the Spawner Information has bugs
and yes they do Spawn Mobs but the main problem the Spawn delay 15 seconds is like 5 Minutes IRL
![image](https://user-images.githubusercontent.com/112314692/188170059-716927bf-8141-4d9a-b127-87a4e4fb5be9.png)

**Comment by OmerBenGera** [comment]
Switch to paper/taco/spigot, let me know if it still happens

**Comment by realgamerk** [comment]
No issues on PaperMC and FlameSpigot
only on Taco and WindSpigot

**Comment by OmerBenGera** [comment]
For no reason, the spigot jar thinks the event should be fired async while that's not the case.
Try contacting WindSpigot developers, show them WS's code, maybe they'll know why it occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by nivcoo** [comment]
Hello, i've same issue here

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If you still have this issue, make sure you let me know by replying here.
