### ISSUE TITLE
Spawner broke

### ISSUE THREAD

**Issue by ItzAndriss** [BG-Software-LLC/WildStacker#622]
### Minecraft's Version

1.18.2 Purpur

### Plugin's Version

3.8.1

### Describe the bug

I broke the spawner but I got the Pig spawer

Error in console:
`[06:35:40 WARN]: [SuperiorSkyblock2] Task #1422 for SuperiorSkyblock2 v1.11.1 generated an exception
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.nms.v1_18_R2.mapping.net.minecraft.world.level.block.entity.TileEntity.getHandle()" because "mobSpawner" is null
        at com.bgsoftware.superiorskyblock.nms.v1_18_R2.NMSWorldImpl.listenSpawner(NMSWorldImpl.java:133) ~[SuperiorSkyblock2-1.11.1.jar:?]
        at com.bgsoftware.superiorskyblock.module.upgrades.type.UpgradeTypeSpawnerRates.lambda$handleSpawnerPlace$1(UpgradeTypeSpawnerRates.java:50) ~[SuperiorSkyblock2-1.11.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### To Reproduce

I write this in the description

**Comment by OmerBenGera** [comment]
The error comes from SuperiorSkyblock.
Also, the issue was already been fixed in the plugin. Update both plugins to their latest dev builds.
