### ISSUE TITLE
BUG STACKMOB INVINCIBLE WITH LAVA AND FIRE ASPECT

### ISSUE THREAD

**Issue by niriaaa** [BG-Software-LLC/WildStacker#625]
### Minecraft's Version

1.18.2 PURUPUR

### Plugin's Version

Last dev build

### Describe the bug

Hello,

The bug is quite simple if players try to kill stack mob via sword with fire aspect enchantment or via lava the stack mob never decreases and the stack mob is therefore invisible.

I also have passive monster stack-mob that never die at all.

These are very problematic bugs

Thanks

### To Reproduce

Using fireaspect 2 and lava on stackmob.

**Comment by niriaaa** [comment]
[05:02:11] [Server thread/WARN]: [WildStacker] Task #505626 for WildStacker v2022.5 generated an exception
java.lang.IllegalArgumentException: The entity-type EXPERIENCE_ORB is not a stackable entity.
	at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:76) ~[WildStacker-2022.5 (1).jar:?]
	at com.bgsoftware.wildstacker.nms.v1182.NMSAdapter.createEntity(NMSAdapter.java:190) ~[WildStacker-2022.5 (1).jar:?]
	at com.bgsoftware.wildstacker.nms.v1182.NMSAdapter.spawnExpOrb(NMSAdapter.java:202) ~[WildStacker-2022.5 (1).jar:?]
	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.spawnExp(EntityUtils.java:152) ~[WildStacker-2022.5 (1).jar:?]
	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:209) ~[WildStacker-2022.5 (1).jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Update the plugin to latest dev build, already been patched.
