### ISSUE TITLE
Could not pass event EntityDeathEvent to WildStacker error

### ISSUE THREAD

**Issue by OreoKirby** [BG-Software-LLC/WildStacker#641]
### Minecraft's Version

Minecraft 1.19.2
Paper 210

### Plugin's Version

2022.5-b374

### Describe the bug

This error is popping up semi-regularly and sometimes in rapid succession in the server console:
```
[Server thread/ERROR]: Could not pass event EntityDeathEvent to WildStacker v2022.5-b374
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation$Result.isCancelEvent()" because "this.monitorEntityDamageEventResult" is null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamageMonitor(EntitiesListener.java:292) ~[WildStacker-2022.5-b374.jar:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:287) ~[WildStacker-2022.5-b374.jar:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.onCustomEntityDeath(EntitiesListener.java:172) ~[WildStacker-2022.5-b374.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor695.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-210]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:878) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1751) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1648) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:318) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2072) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2983) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2905) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-210]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-210]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
### To Reproduce

Did not find a specific way to trigger this, but noticed it while a player was using a mob grinder.

### Additional Information

"this.monitorEntityDamageEventResult" is null

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed
