### ISSUE TITLE
Mobs not Dying

### ISSUE THREAD

**Issue by Jennifxrr** [BG-Software-LLC/WildStacker#644]
### Minecraft's Version

1.8.9 FlamePaper

### Plugin's Version

Dev Build #376 13/10/2022 21:40:42

### Describe the bug

It is not allowing me to kill mobs like Cows and witches, however it's allowing me to kill villagers and some other mobs. 

### To Reproduce

Just kill mobs, thats all I did.

**Comment by OmerBenGera** [comment]
Take a video of the issue please.
Look for errors in console.

**Comment by MrButtersDEV** [comment]
Hi, idk if this is the same issue but I am able to kill the first mob but not the second and then on.
https://youtu.be/7Q2-qZWAbCk

Latest stable version 2022.5, 1.19.2, no console errors

**Comment by OmerBenGera** [comment]
> Hi, idk if this is the same issue but I am able to kill the first mob but not the second and then on. https://youtu.be/7Q2-qZWAbCk
> 
> Latest stable version 2022.5, 1.19.2, no console errors

Update to latest dev build

**Comment by OmerBenGera** [comment]
@Jennifxrr

**Comment by Sulphinx** [comment]
This didn't fix it Omer. I updated to latest version, but their still immortal.

**Comment by Sulphinx** [comment]
Only one i could find was this:
[18:55:38 WARN]: [WildStacker] Task #6751400 for WildStacker v2022.5 generated an exception
java.lang.IllegalArgumentException: The entity-type EXPERIENCE_ORB is not a stackable entity.
        at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:76) ~[?:?]
        at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.createEntity(NMSAdapter.java:128) ~[?:?]
        at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.spawnExpOrb(NMSAdapter.java:140) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.EntityUtils.spawnExp(EntityUtils.java:152) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:209) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
        
        But that has nothing to do with it.

**Comment by Sulphinx** [comment]
Oh and im using 1.8.8 paperspigot*

**Comment by OmerBenGera** [comment]
> Only one i could find was this: [18:55:38 WARN]: [WildStacker] Task #6751400 for WildStacker v2022.5 generated an exception java.lang.IllegalArgumentException: The entity-type EXPERIENCE_ORB is not a stackable entity. at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:76) ~[?:?] at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.createEntity(NMSAdapter.java:128) ~[?:?] at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.spawnExpOrb(NMSAdapter.java:140) ~[?:?] at com.bgsoftware.wildstacker.utils.entity.EntityUtils.spawnExp(EntityUtils.java:152) ~[?:?] at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:209) ~[?:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
> 
> ```
>     But that has nothing to do with it.
> ```

Update to latest dev build...

**Comment by OmerBenGera** [comment]
I am closing this as it seems every person that has this issue did not updated (or in other words, the issue was already been fixed)
