### ISSUE TITLE
Errors.. and stacked drop don't work if the mob is one shot

### ISSUE THREAD

**Issue by Weyl1** [BG-Software-LLC/WildStacker#646]
### Minecraft's Version

Purpur-1.19.2-1824

### Plugin's Version

WildStacker-2022.5-b376

### Describe the bug

If the player kills a mob, the drop is not multiplied according to the monster in the stack and counts as 1 monster killed

### To Reproduce

Kill the monster in one shot to reproduce the bug

### Additional Information
https://www.youtube.com/watch?v=VDu3s6E82e8
_No response_

**Comment by Weyl1** [comment]
>.... [19:19:15 ERROR]: Could not pass event PlayerInteractEntityEvent to WildStacker v2022.5-b376
java.lang.NoSuchMethodError: 'boolean com.bgsoftware.wildstacker.nms.NMSAdapter.isAnimalFood(org.bukkit.entity.Animals, org.bukkit.inventory.ItemStack)'
at com.guillaumevdn.questcreator.integration.wildstacker.IntegrationInstanceWildStacker.lambda$0(IntegrationInstanceWildStacker.java:44) ~[QuestCreator.jar:?]
at com.guillaumevdn.gcore.lib.integration.IntegrationEvent$2.execute(IntegrationEvent.java:73) ~[GCore.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1824]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at com.ticxo.modelengine.nms.v1_19_1_R1.network.interact.PatchedInteractHandler$1.performInteraction(PatchedInteractHandler.java:92) ~[Model-Engine-R3.0.1.jar:?]
at com.ticxo.modelengine.nms.v1_19_1_R1.network.interact.PatchedInteractHandler$1.a(PatchedInteractHandler.java:129) ~[Model-Engine-R3.0.1.jar:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
at com.ticxo.modelengine.nms.v1_19_1_R1.network.interact.ServerboundInteractPacketWrapper.a(ServerboundInteractPacketWrapper.java:46) ~[Model-Engine-R3.0.1.jar:?]
at com.ticxo.modelengine.nms.v1_19_1_R1.network.interact.PatchedInteractHandler.handleInteract(PatchedInteractHandler.java:86) ~[Model-Engine-R3.0.1.jar:?]
at com.ticxo.modelengine.nms.v1_19_1_R1.network.interact.ServerboundInteractPacketWrapper.a(ServerboundInteractPacketWrapper.java:30) ~[Model-Engine-R3.0.1.jar:?]
at com.ticxo.modelengine.nms.v1_19_1_R1.network.interact.ServerboundInteractPacketWrapper.a(ServerboundInteractPacketWrapper.java:11) ~[Model-Engine-R3.0.1.jar:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1824]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1824]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
This is an error from com.guillaumevdn.questcreator, and not related to WildStacker.
They hooked into WildStacker but they use internal methods of the plugin, which they shouldn't.
