### ISSUE TITLE
Console Errors lead to server latency.

### ISSUE THREAD

**Issue by nexlemav** [BG-Software-LLC/WildStacker#659]
### Minecraft's Version

git-purpur-1761 (MC: 1.19.2)

### Plugin's Version

2022.5

### Describe the bug

[29.10 22:17:27] [Server] [WARN] [WildStacker] Task #2534863 for WildStacker v2022.5 generated an exception
[29.10 22:17:27] [Server] java.lang.IllegalArgumentExceptionThe entity-type EXPERIENCE_ORB is not a stackable entity.
[29.10 22:17:27] [Server] 	at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:76) ~[WildStacker-2022.5.jar:?]
[29.10 22:17:27] [Server] 	at com.bgsoftware.wildstacker.nms.v1192.NMSAdapter.createEntity(NMSAdapter.java:190) ~[WildStacker-2022.5.jar:?]
[29.10 22:17:27] [Server] 	at com.bgsoftware.wildstacker.nms.v1192.NMSAdapter.spawnExpOrb(NMSAdapter.java:202) ~[WildStacker-2022.5.jar:?]
[29.10 22:17:27] [Server] 	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.spawnExp(EntityUtils.java:152) ~[WildStacker-2022.5.jar:?]
[29.10 22:17:27] [Server] 	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:209) ~[WildStacker-2022.5.jar:?]
[29.10 22:17:27] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1761]
[29.10 22:17:27] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Not sure how this is being triggered

### Additional Information

When the console errors occur, the server eventually halts and times everyone out. Server does not crash as far as I can tell.

**Comment by OmerBenGera** [comment]
Update to latest dev build
