### ISSUE TITLE
Plugin wont start on 1.7.10.

### ISSUE THREAD

**Issue by Zilacon** [BG-Software-LLC/WildStacker#663]
### Minecraft's Version

1.7.10 Crucible

### Plugin's Version

v2022.6-b381

### Describe the bug

On start up get this error:
```
[04:06:42 INFO]: [WildStacker] Enabling WildStacker v2022.6-b381
[04:06:42 INFO]: [WildStacker] ******** ENABLE START ********
[04:06:42 ERROR]: Error occurred while enabling WildStacker v2022.6-b381 (Is it up to date?)
java.lang.NoSuchMethodError: guava10/com/google/common/collect/Sets.newConcurrentHashSet()Ljava/util/Set; (loaded from jar:file:/home/apoc/Servers/1710-Servers/1710Pack/1710.jar!/guava10/com/google/common/collect/Sets.class by net.minecraft.launchwrapper.LaunchClassLoader@422e8d18) called from class com.bgsoftware.wildstacker.handlers.DataHandler (loaded from file:/home/apoc/Servers/1710-Servers/1710Pack/plugins/WildStacker-2022.6-b381.jar by org.bukkit.plugin.java.PluginClassLoader@9de5f093).
        at com.bgsoftware.wildstacker.handlers.DataHandler.<init>(DataHandler.java:46) ~[?:?]
        at com.bgsoftware.wildstacker.WildStackerPlugin.onEnable(WildStackerPlugin.java:150) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-dev-4eab54a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:362) [JavaPluginLoader.class:1.7.10-dev-4eab54a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [SimplePluginManager.class:1.7.10-dev-4eab54a]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:402) [CraftServer.class:1.7.10-dev-4eab54a]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:336) [CraftServer.class:1.7.10-dev-4eab54a]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:514) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:488) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:448) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:827) [?:1.8.0_345]
```

### To Reproduce

Use plugin on a 1.7.10 Hybrid Server (Thermos/Crucible)

### Additional Information

No config or other logs generated.

**Comment by OmerBenGera** [comment]
Try it on Spigot for 1.7.10, let me know if it works

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
