### ISSUE TITLE
Console spam on newest version

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#672]
### Minecraft's Version

1.19.2

### Plugin's Version

Latest dev build b387

### Describe the bug

Console spam:

[20.11 16:27:05] [Server] [ERROR] Could not pass event EntityDamageByBlockEvent to WildStacker v2022.6-b387
[20.11 16:27:05] [Server] java.lang.NoSuchMethodError'org.bukkit.inventory.meta.ItemMeta$Spigot org.bukkit.inventory.meta.ItemMeta.spigot()'
[20.11 16:27:05] [Server] 	at com.bgsoftware.wildstacker.utils.items.ItemUtils.isUnbreakable(ItemUtils.java:405) ~[WildStacker-2022.6-b387.jar:?]
[20.11 16:27:05] [Server] 	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:126) ~[WildStacker-2022.6-b387.jar:?]
[20.11 16:27:05] [Server] 	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:274) ~[WildStacker-2022.6-b387.jar:?]
[20.11 16:27:05] [Server] 	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:208) ~[WildStacker-2022.6-b387.jar:?]
[20.11 16:27:05] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor784.execute(Unknown Source) ~[?:?]
[20.11 16:27:05] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[20.11 16:27:05] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[20.11 16:27:05] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[20.11 16:27:05] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1056) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:964) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1187) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2122) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1369) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.monster.Guardian.hurt(Guardian.java:322) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.level.block.CampfireBlock.entityInside(CampfireBlock.java:99) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:1022) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1522) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1234) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.Entity.move(Entity.java:1161) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2871) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2826) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.monster.Guardian.travel(Guardian.java:340) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3353) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.Mob.aiStep(Mob.java:640) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.monster.Guardian.aiStep(Guardian.java:281) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2975) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1192) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:730) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[?:?]
[20.11 16:27:05] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
[20.11 16:27:05] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

kill mobs with falling

**Comment by ArmonicPvP** [comment]
I believe this happens when they are taking damage on campfires

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still happens

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know by replying.
