### ISSUE TITLE
Error when using spawner minecarts

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#673]
### Minecraft's Version

1.19.2

### Plugin's Version

2022.6

### Describe the bug

[21.11 00:52:43] [Server] [ERROR] Could not pass event PreSpawnerSpawnEvent to WildStacker v2022.6
[21.11 00:52:43] [Server] java.lang.IllegalArgumentExceptionOnly spawners can be applied to StackedSpawner object
[21.11 00:52:43] [Server] 	at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:60) ~[WildStacker-2022.6.jar:?]
[21.11 00:52:43] [Server] 	at com.bgsoftware.wildstacker.listeners.SpawnersListener$PaperSpawnersListener.onPreSpawnSpawner(SpawnersListener.java:765) ~[WildStacker-2022.6.jar:?]
[21.11 00:52:43] [Server] 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[21.11 00:52:43] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[21.11 00:52:43] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[21.11 00:52:43] [Server] 	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[21.11 00:52:43] [Server] 	at net.minecraft.world.level.BaseSpawner.serverTick(BaseSpawner.java:140) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.world.entity.vehicle.MinecartSpawner.lambda$createTicker$0(MinecartSpawner.java:40) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.world.entity.vehicle.MinecartSpawner.tick(MinecartSpawner.java:76) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1192) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:730) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[?:?]
[21.11 00:52:43] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
[21.11 00:52:43] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

spawn a spawner minecart (essentials cmd /spawnmob spawnerminecart)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
