### ISSUE TITLE
Players dropping items are just being vanished

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/WildStacker#688]
### Minecraft's Version

1.12 paper

### Plugin's Version

WildStacker-2022.6-b391

### Describe the bug

So as you can see the mobs don't drop items aswell the items being dropped by the player is not working aswell

### To Reproduce

https://images-ext-1.discordapp.net/external/Rjqio3-DPbvm_gZQhcAN5dXo6aYbTsXBlLw7zuuwolg/https/i.imgur.com/MvOMs1d.mp4

**Comment by OmerBenGera** [comment]
Try replicating the issue on a server with only WildStacker installed.
If it still occurs, reupload your video to a proper online streaming service (youtube, for example) and send me the exact output of /version.

**Comment by Superalex0102** [comment]
> Try replicating the issue on a server with only WildStacker installed. If it still occurs, reupload your video to a proper online streaming service (youtube, for example) and send me the exact output of /version.

```
[16:10:20 ERROR]: Could not pass event PlayerInteractEntityEvent to WildStacker v2022.6-b391
java.lang.NoSuchMethodError: 'boolean com.bgsoftware.wildstacker.nms.NMSAdapter.isAnimalFood(org.bukkit.entity.Animals, org.bukkit.inventory.ItemStack)'
        at com.guillaumevdn.questcreator.integration.wildstacker.IntegrationInstanceWildStacker.lambda$0(IntegrationInstanceWildStacker.java:44) ~[?:?]
        at com.guillaumevdn.gcore.lib.integration.IntegrationEvent$2.execute(IntegrationEvent.java:73) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1682) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-77cce823]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
is this regarded?

**Comment by OmerBenGera** [comment]
> > Try replicating the issue on a server with only WildStacker installed. If it still occurs, reupload your video to a proper online streaming service (youtube, for example) and send me the exact output of /version.
> 
> ```
> [16:10:20 ERROR]: Could not pass event PlayerInteractEntityEvent to WildStacker v2022.6-b391
> java.lang.NoSuchMethodError: 'boolean com.bgsoftware.wildstacker.nms.NMSAdapter.isAnimalFood(org.bukkit.entity.Animals, org.bukkit.inventory.ItemStack)'
>         at com.guillaumevdn.questcreator.integration.wildstacker.IntegrationInstanceWildStacker.lambda$0(IntegrationInstanceWildStacker.java:44) ~[?:?]
>         at com.guillaumevdn.gcore.lib.integration.IntegrationEvent$2.execute(IntegrationEvent.java:73) ~[?:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1682) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-77cce823]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> ```
> 
> is this regarded?

Yes, might be.
Get rid of that plugin (that for no reason uses internal methods of the plugin) and check if it works again.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Superalex0102** [comment]
> Any news regarding this?

I updated and don't seem to have this issue anymore

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> I updated and don't seem to have this issue anymore

Did you get rid of the plugin that used internal methods of the plugin?

**Comment by Superalex0102** [comment]
Yeah

**Comment by OmerBenGera** [comment]
> Yeah

So that was probably the issue
Contact their developer and tell them to not use internal methods of the plugin. The plugin has a public API and only these methods should be used.
I am closing this
