### ISSUE TITLE
Cannot pick up spawners

### ISSUE THREAD

**Issue by Devs52** [BG-Software-LLC/WildStacker#746]
### Minecraft's Version

TacoSpigot 1.8.8

### Plugin's Version

2022.6

### Describe the bug

Cannot pick up spawners, when mining or taking them out of the menu they just despawn
https://youtu.be/a1_vljrwYp4

Console Error when trying to collect:

[06:14:40 ERROR]: Could not pass event BlockBreakEvent to WildStacker v2022.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-TacoSpigot-1be69cbf]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-TacoSpigot-1be69cbf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-1be69cbf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-TacoSpigot-1be69cbf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:640) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-TacoSpigot-1be69cbf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [server.jar:git-TacoSpigot-1be69cbf]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [server.jar:git-TacoSpigot-1be69cbf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_312]
        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_SilkSpawners.handleSpawnerBreak(SpawnersProvider_SilkSpawners.java:89) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:110) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:340) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-TacoSpigot-1be69cbf]
        ... 18 more
[06:14:41 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@3ed47d2a
[06:14:41 WARN]:        at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source)
[06:14:41 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:14:41 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[06:14:41 WARN]:        at com.bgsoftware.common.reflection.ReflectMethod.invokeWithDef(ReflectMethod.java:71)
[06:14:41 WARN]:        at com.bgsoftware.common.reflection.ReflectMethod.invoke(ReflectMethod.java:63)
[06:14:41 WARN]:        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_SilkSpawners.getCreatureName(SpawnersProvider_SilkSpawners.java:133)
[06:14:41 WARN]:        at com.bgsoftware.wildstacker.hooks.SpawnersProvider_SilkSpawners.handleSpawnerBreak(SpawnersProvider_SilkSpawners.java:89)
[06:14:41 WARN]:        at com.bgsoftware.wildstacker.listeners.SpawnersListener.handleSpawnerBreak(SpawnersListener.java:110)
[06:14:41 WARN]:        at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockBreak(SpawnersListener.java:340)
[06:14:41 WARN]:        at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source)
[06:14:41 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:14:41 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[06:14:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[06:14:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[06:14:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:14:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[06:14:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:640)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[06:14:41 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:14:41 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[06:14:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[06:14:41 WARN]:        at java.lang.Thread.run(Thread.java:748)

### To Reproduce

I don't know why it's happening.

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it works
Also, run /version SilkSpawners and send me the output of the command

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
