### ISSUE TITLE
Arrow pickup spam console

### ISSUE THREAD

**Issue by elima151** [BG-Software-LLC/WildStacker#774]
### Minecraft's Version

Paper-1.8.8

### Plugin's Version

2023.1

### Describe the bug

when I shoot arrows with an enchant called "volley" it makes me shoot more than one arrow when grabbing the arrows from the ground the console spams an error.

console error spam:

[17:23:13 ERROR]: Could not pass event PlayerPickupItemEvent to WildStacker v2023.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader.lambda$createRegisteredListeners$1(JavaPluginLoader.java:281) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:488) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:473) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.EntityArrow.d(EntityArrow.java:425) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:480) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.EntityHuman.m(EntityHuman.java:471) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1287) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:200) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:281) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:327) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:6) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$2(MinecraftServer.java:566) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:?]
Caused by: java.lang.ClassCastException: net.minecraft.server.v1_8_R3.EntityArrow cannot be cast to net.minecraft.server.v1_8_R3.EntityItem
        at com.bgsoftware.wildstacker.nms.v1_8_R3.serializers.DefaultDataSerializer.loadItem(DefaultDataSerializer.java:131) ~[?:?]
        at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.loadItem(NMSAdapter.java:269) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.DataSerializer_Default.loadItem(DataSerializer_Default.java:33) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedItem(SystemHandler.java:229) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedItem.ofBypass(WStackedItem.java:68) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedItem.of(WStackedItem.java:64) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.events.EventsListener$PlayerPickup.onPlayerPickupItem(EventsListener.java:137) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.lambda$createRegisteredListeners$1(JavaPluginLoader.java:279) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8-R0.2-SNAPSHOT]
        ... 24 more

### To Reproduce

I don't know

### Additional Information

config.yml: https://pastebin.com/PdBbbfmS

**Comment by OmerBenGera** [comment]
I didn't manage to replicate the issue myself, it's probably something with the custom enchantment that caused it to occur.
However, I tried to patch it in the latest dev build, so let me know if it works.

**Comment by elima151** [comment]
if it's fixed it doesn't give me any error

**Comment by OmerBenGera** [comment]
Does it give any errors now?

**Comment by elima151** [comment]
no one is great
