### ISSUE TITLE
Latest Wild Stacker version, dosen't work for paper 1.19.3, build 319.

### ISSUE THREAD

**Issue by nullerking** [BG-Software-LLC/WildStacker#792]
### Minecraft's Version

Paper 1.19.3, build 319

### Plugin's Version

2023.1 | Mar 31, 2023

### Describe the bug

Dosen't work.
Error:

[10:34:10 ERROR]: Could not pass event BlockPlaceEvent to WildStacker v2023.1
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.MobSpawnerData.a()" because "net.minecraft.world.level.block.entity.TileEntityMobSpawner.d().f" is null
        at org.bukkit.craftbukkit.v1_19_R2.block.CraftCreatureSpawner.getSpawnedType(CraftCreatureSpawner.java:18) ~[paper-1.19.3.jar:git-Paper-319]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:54) ~[WildStacker-2023.1.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:47) ~[WildStacker-2023.1.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:257) ~[WildStacker-2023.1.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:246) ~[WildStacker-2023.1.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:64) ~[WildStacker-2023.1.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:59) ~[WildStacker-2023.1.jar:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:150) ~[WildStacker-2023.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-319]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:396) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:403) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:587) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1963) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-319]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Download wild stacker on paper 1.19.3, build 319 server.

**Comment by OmerBenGera** [comment]
This is a bug with Spigot/Paper, not related to WildStacker.
`CraftCreatureSpawner.getSpawnedType` fails and this is a Bukkit method.

**Comment by nullerking** [comment]
Why don't you make your earlier versions downloadable?
Because earlier versions are often compatible with the older server versions aswell.
