### ISSUE TITLE
1.8.8 resetting a world via plugin gives warn spam in console

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildStacker#796]
### Minecraft's Version

WineSpigot 1.8.8

### Plugin's Version

2022.6 b-395(most stable for 1.8.8)

### Describe the bug

There's this raiding world, and it resets the world on an interval, and whenever it's resetting, this warn spams and disappears after the world has been reset, its not a huge error as it's not doing anything wrong in the server but the warn on console is annoying.

### To Reproduce

FactionsKore(I can give u access temporarily) create a raidworld, reset it and see wildstacker spamming this warn in console.

### Additional Information

CONSOLE WARN:
```
[13:26:33 WARN]: [FactionsKore] Task #348641 for FactionsKore v1.0 generated an exception
java.lang.AbstractMethodError: com.bgsoftware.wildstacker.nms.v1_8_R3.world.WorldEntityListener.flagChunkDirty(II)V
        at net.minecraft.server.v1_8_R3.World.flagChunkDirty(World.java:873) ~[server.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.refreshChunk(CraftWorld.java:275) ~[server.jar:1_8_R3]
        at com.golfing8.kore.routpost.RaidOutpost$3.run(RaidOutpost.java:798) ~[FactionsKore-1.3.8.6.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:60) ~[server.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:965) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:870) [server.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:760) [server.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by OmerBenGera** [comment]
Please link me with your spigot jar.

**Comment by illudota** [comment]
It is winespigot, I will dm u in discord? its a private jar

**Comment by illudota** [comment]
Contact me on discord for the Jar file pls, it is a paid one so I don't have access to posting link here.
abujuju#8103, I cannot add you that's why.

**Comment by illudota** [comment]
Omer here is the spigot jar, but there is a license key, please dm me or ping me on the discord channel, so I can give it to you.
https://drive.google.com/file/d/14TMoz0WqhQUM_Ww30fMu8vnc4r2WKT5Y/view?usp=sharing

**Comment by OmerBenGera** [comment]
I opened a ticket for you on our discord server.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue continues make sure you let me know
