### ISSUE TITLE
Echopet Error

### ISSUE THREAD

**Issue by Enkixp** [BG-Software-LLC/WildStacker#810]
### Minecraft's Version

1.18, purper

### Plugin's Version

2023.1

### Describe the bug

Whenever i type /pet and use echopet pets the console gives the error

### To Reproduce

[13:40:14 INFO]: Enkix issued server command: /pet bat
[13:40:27 INFO]: Enkix issued server command: /pet bat
[13:40:28 INFO]: Enkix issued server command: /spawn
[13:40:33 INFO]: Enkix issued server command: /pet bat
[13:40:33 WARN]: [WildStacker] Task #27582 for WildStacker v2023.1 generated an exception
java.lang.NoSuchMethodError: 'com.dsh105.echopet.compat.api.entity.IPet com.dsh105.echopet.compat.api.event.PetPreSpawnEvent.getPet()'
        at com.bgsoftware.wildstacker.hooks.EchoPetHook$1.lambda$onEchoPetSpawn$0(EchoPetHook.java:21) ~[WildStacker-2023.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Additional Information

I don't know why echopet is giving error to wildstacker

**Comment by Enkixp** [comment]
#63 from jenkins

**Comment by OmerBenGera** [comment]
Link to download?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues make sure you let me know
