### ISSUE TITLE
error console

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/WildStacker#812]
### Minecraft's Version

Pufferfish version git-Pufferfish-11 (MC: 1.20.1)

### Plugin's Version

last

### Describe the bug

[15:38:18 WARN]: [WildStacker] Task #4444816 for WildStacker v2023.2-b5 generated an exception
io.github.thebusybiscuit.slimefun4.api.exceptions.WrongItemStackException: You probably wanted to alter a different ItemStack: GN_GUARDIAN_FIN is not mutable.
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack.validate(SlimefunItemStack.java:264) ~[Slimefun4 - DEV 1068 (git cab97).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack.setAmount(SlimefunItemStack.java:258) ~[Slimefun4 - DEV 1068 (git cab97).jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$1(DeathSimulation.java:192) ~[WildStacker-2023.2-b5.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:192) ~[WildStacker-2023.2-b5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-11]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

no error

**Comment by OmerBenGera** [comment]
Slimefun injects a weird ItemStack to the drops of EntityDeathEvent and does not let any plugin change its amount.
This is not a behavior that should occur and should be reported to Slimefun.
