### ISSUE TITLE
WildStacker throws NoSuchMethod Error when attempting to summon a MiniaturePet from the latest version

### ISSUE THREAD

**Issue by SaberSupe** [BG-Software-LLC/WildStacker#828]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-20 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker 2023.2
MiniaturePets 3.0.5
https://www.spigotmc.org/resources/1-13-1-20-1-%E2%AD%95-miniaturepets-custom-3d-pets-%E2%AD%95-no-resource-texture-pack-%E2%9C%85-30-sale.23991/

### Describe the bug

When you summon a pet using MiniaturePets version 3.0.5, WildStacker version 2023.2 throws the following error:

[16:43:47 INFO]: SaberSupreme issued server command: /mpet pet Duck
[16:43:47 ERROR]: Could not pass event PetFinishedSpawnEvent to WildStacker v2023.2
java.lang.NoSuchMethodError: 'org.bukkit.entity.LivingEntity com.kirelcodes.miniaturepets.pets.Pet.getNavigator()'
        at com.bgsoftware.wildstacker.hooks.MiniaturePetsHook$1.onMiniaturePetSpawn(MiniaturePetsHook.java:19) ~[WildStacker-2023.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:git-Pufferfish-20]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.kirelcodes.miniaturepets.pets.Pet.lambda$new$1(Pet.java:110) ~[MiniaturePets-3.0.5.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at com.kirelcodes.miniaturepets.data.adapters.AbstractDataManager.lambda$complete$3(AbstractDataManager.java:75) ~[MiniaturePets-3.0.5.jar:?]
        at com.kirelcodes.miniaturepets.data.adapters.AbstractDataManager$1.run(AbstractDataManager.java:107) ~[MiniaturePets-3.0.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-20]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Attempt to summon a pet while MiniaturePets 3.0.5 and WildStacker 2023.2 are installed.

**Comment by SaberSupe** [comment]
It seems MiniaturePets changed the api, I changed line 19 in the MiniaturePets hook to the below and it fixes the above error
LivingEntity livingEntity = e.getPet().getPet().getBaseEntity();

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
