### ISSUE TITLE
Errors when running the server with PlotSquared installed

### ISSUE THREAD

**Issue by mathemaciel** [BG-Software-LLC/WildStacker#864]
### Minecraft's Version

1.20.2

### Plugin's Version

dev #22

### Describe the bug

error when starting the server, when restarting the server or connecting this message appears right after completing the server connection

### To Reproduce

start server or restart server

### Additional Information

[22:26:26 WARN]: [WildStacker] Task #37 for WildStacker v2023.3-b22 generated an exception
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/api/PlotAPI
        at com.bgsoftware.wildstacker.hooks.ClaimsProvider_PlotSquaredLegacy.<init>(ClaimsProvider_PlotSquaredLegacy.java:10) ~[WildStacker-2023.3-b22.jar:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.createInstance(ProvidersHandler.java:580) ~[WildStacker-2023.3-b22.jar:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.loadClaimsProvider(ProvidersHandler.java:197) ~[WildStacker-2023.3-b22.jar:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:82) ~[WildStacker-2023.3-b22.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2087]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2087]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1113) ~[purpur-1.20.2.jar:git-Purpur-2087]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2087]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.api.PlotAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 14 more

**Comment by OmerBenGera** [comment]
What version of PlotSquared do you use?

**Comment by mathemaciel** [comment]
lasted version of v7

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue continues let me know
