### ISSUE TITLE
Dropping more items than 64x and picking it back up will result in 64x pickup.

### ISSUE THREAD

**Issue by danekoenders** [BG-Software-LLC/WildStacker#865]
### Minecraft's Version

Minecraft version: 1.20.2
Paper 1.20.2

### Plugin's Version

2023.3

### Describe the bug

When dropping items on the ground with item stacking toggled on, it will drop let's say 128 on the ground. But when picking it up it gives back just 64.

### To Reproduce

Drop 128 items on the ground (2 stacks) and pick it back up. This will give 64.

**Comment by OmerBenGera** [comment]
Seems to work fine for me.
Make sure you install latest dev build, as well as try it on a server with only WildStacker installed.
Let me know if it works.

**Comment by danekoenders** [comment]
@OmerBenGera It still doesn't seem to work.

I get this error with the latest dev build:

```
Could not pass event ItemMergeEvent to WildStacker v2023.3-b32
20.12 11:16:04 [Server] [INFO] java.lang.NoSuchMethodError: 'net.minecraft.world.entity.item.EntityItem org.bukkit.craftbukkit.v1_20_R2.entity.CraftItem.getHandle()'
20.12 11:16:04 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1_20_2.NMSEntities.isDroppedItem(NMSEntities.java:759) ~[WildStacker-2023.3-b32.jar:?]
20.12 11:16:04 [Server] [INFO] at com.bgsoftware.wildstacker.utils.items.ItemUtils.isStackable(ItemUtils.java:421) ~[WildStacker-2023.3-b32.jar:?]
20.12 11:16:04 [Server] [INFO] at com.bgsoftware.wildstacker.listeners.ItemsListener$MergeListener.onItemMerge(ItemsListener.java:216) ~[WildStacker-2023.3-b32.jar:?]
20.12 11:16:04 [Server] [INFO] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
20.12 11:16:04 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-"71a1787"]
20.12 11:16:04 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
20.12 11:16:04 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:04 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:04 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
20.12 11:16:04 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callItemMergeEvent(CraftEventFactory.java:842) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:04 [Server] [INFO] at net.minecraft.world.entity.item.ItemEntity.merge(ItemEntity.java:329) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.world.entity.item.ItemEntity.tryToMerge(ItemEntity.java:301) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.world.entity.item.ItemEntity.mergeWithNeighbours(ItemEntity.java:279) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.world.entity.item.ItemEntity.tick(ItemEntity.java:186) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:07 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-"71a1787"]
20.12 11:16:07 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by OmerBenGera** [comment]
Update both Paper and the plugin, it will fix itself.

**Comment by OmerBenGera** [comment]
Was it fixed?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
