### ISSUE TITLE
Could not pass event LoggingPlayerInteractEvent to WildStacker v2023.3-b26

### ISSUE THREAD

**Issue by moonies44** [BG-Software-LLC/WildStacker#898]
### Minecraft's Version

Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Plugin's Version

 WildStacker version 2023.3-b26

### Describe the bug

very fast console spam

### To Reproduce

No idea how to reproduce it does it whenever it wants

### Additional Information

[01:37:19 ERROR]: Could not pass event LoggingPlayerInteractEvent to WildStacker v2023.3-b26
java.lang.IllegalArgumentException: Cannot get used hand for event: class com.sk89q.worldguard.bukkit.event.debug.LoggingPlayerInteractEvent
        at com.bgsoftware.wildstacker.utils.items.ItemUtils.getHand(ItemUtils.java:278) ~[WildStacker-2023.3-b26.jar:?]
        at com.bgsoftware.wildstacker.utils.items.ItemUtils.isOffHand(ItemUtils.java:359) ~[WildStacker-2023.3-b26.jar:?]
        at com.bgsoftware.wildstacker.listeners.BarrelsListener.onBarrelClick(BarrelsListener.java:227) ~[WildStacker-2023.3-b26.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1519.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        
        
        
        
        https://mclo.gs/kZVRZfX

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs let me know
