### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by RequaizeN** [BG-Software-LLC/WildStacker#900]
### Minecraft's Version

1.20.4 paperspigot

### Plugin's Version

WildStacker v2023.3-b40

### Describe the bug

When I kill a mobs, it gives an error on the console.

### To Reproduce

When I kill a mobs, it gives an error on the console.

### Additional Information

[04:22:28 ERROR]: Could not pass event EntityDeathEvent to WildStacker v2023.3-b40
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDamageEvent.(org.bukkit.entity.Entity, org.bukkit.event.entity.EntityDamageEvent$DamageCause, java.util.Map, java.util.Map)'
at com.bgsoftware.wildstacker.listeners.EntitiesListener.createDamageEvent(EntitiesListener.java:1002) ~[WildStacker-2023.3-b40.jar:?]
at com.bgsoftware.wildstacker.listeners.EntitiesListener.onCustomEntityDeath(EntitiesListener.java:175) ~[WildStacker-2023.3-b40.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor736.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-423]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-423]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-423]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:985) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1839) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1733) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1557) ~[?:?]
at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2787) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2711) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-423]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-423]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
What version of Paper do you use?
Gice me the exact output of /version

**Comment by OmerBenGera** [comment]
Try updating to latest version of Paper, let me know if it still occurs

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
