### ISSUE TITLE
It gaves me this bug

### ISSUE THREAD

**Issue by realgamerk** [BG-Software-LLC/WildStacker#909]
### Minecraft's Version

windspigot

### Plugin's Version

2023.3

### Describe the bug

[00:58:06 ERROR]: Could not pass event EntityDamageByEntityEvent to WildStacker v2023.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:168) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:670) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:574) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:707) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1217) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:793) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44) ~[server.jar:]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:]
        at eu.decentsoftware.holograms.api.nms.PacketHandlerCustom.channelRead(PacketHandlerCustom.java:18) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:28) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: EntityUnstackEvent cannot be triggered asynchronously from inside synchronized code.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[server.jar:]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callEntityUnstackEvent(EventsCaller.java:80) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.runUnstack(WStackedEntity.java:306) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.simulateDeath(DeathSimulation.java:94) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamageInternal(EntitiesListener.java:294) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:251) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:211) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor288.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]
        ... 65 more

### To Reproduce

when i damage a mob

**Comment by OmerBenGera** [comment]
Update to latest dev build
Let me know if it still occurs

**Comment by realgamerk** [comment]
Yes it still has the issue

**Comment by OmerBenGera** [comment]
Try it on regular Spigot/Paper, let me know if the issue still occurs.

**Comment by realgamerk** [comment]
Still the issue is still there

**Comment by realgamerk** [comment]
![image_2024-04-27_000411251](https://github.com/BG-Software-LLC/WildStacker/assets/112314692/e5049fb1-f500-4d0e-a332-55260ecbfcf9)

**Comment by realgamerk** [comment]
hooks on CrazyEnchantments too i think thats the problem

**Comment by OmerBenGera** [comment]
What version of Spigot/Paper do you use? I need the exact output of `/version`.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
