### ISSUE TITLE
Bug when using /ws give 

### ISSUE THREAD

**Issue by Nch0001** [BG-Software-LLC/WildStacker#915]
### Minecraft's Version

1.20.4

### Plugin's Version

Tried latest dev-build #53
and latest public release 2024.1
Both give issue

### Describe the bug

Upon using `/ws give Nch001 spawner blaze <number>`
Throws the error:
`https://mcpaste.io/d1ac5b2e5690d4ae` 
for the formatted ver or see below
`
12.05 00:40:55 [Server] INFO Nch001 issued server command: /stacker give Nch001 spawner blaze 12 coal
12.05 00:40:55 [Server] ERROR null
12.05 00:40:55 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'stacker' in plugin WildStacker v2024.1-b53
12.05 00:40:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
12.05 00:40:55 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
12.05 00:40:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
12.05 00:40:55 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
12.05 00:40:55 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
12.05 00:40:55 [Server] INFO Caused by: com.dnyferguson.mineablespawners.nbtapi.NbtApiException: [?]Error while calling the method 'putString(java.lang.String,java.lang.String)', loaded: true, Enum: COMPOUND_SET_STRING, Passed Class: class java.lang.Boolean
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:615) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.nbtapi.NBTCompound.setString(NBTCompound.java:115) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.api.API.getSpawnerFromEntityType(API.java:72) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.bgsoftware.wildstacker.hooks.SpawnersProvider_MineableSpawners.getSpawnerItem(SpawnersProvider_MineableSpawners.java:90) ~[WildStacker-2024.1-b53.jar:?]
12.05 00:40:55 [Server] INFO at com.bgsoftware.wildstacker.command.commands.CommandGive.perform(CommandGive.java:149) ~[WildStacker-2024.1-b53.jar:?]
12.05 00:40:55 [Server] INFO at com.bgsoftware.wildstacker.command.CommandsHandler.onCommand(CommandsHandler.java:56) ~[WildStacker-2024.1-b53.jar:?]
12.05 00:40:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
12.05 00:40:55 [Server] INFO ... 29 more
12.05 00:40:55 [Server] INFO Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
12.05 00:40:55 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
12.05 00:40:55 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
12.05 00:40:55 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
12.05 00:40:55 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:615) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.nbtapi.NBTCompound.setString(NBTCompound.java:115) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.dnyferguson.mineablespawners.api.API.getSpawnerFromEntityType(API.java:72) ~[MineableSpawners-3.1.5.jar:?]
12.05 00:40:55 [Server] INFO at com.bgsoftware.wildstacker.hooks.SpawnersProvider_MineableSpawners.getSpawnerItem(SpawnersProvider_MineableSpawners.java:90) ~[WildStacker-2024.1-b53.jar:?]
12.05 00:40:55 [Server] INFO at com.bgsoftware.wildstacker.command.commands.CommandGive.perform(CommandGive.java:149) ~[WildStacker-2024.1-b53.jar:?]
12.05 00:40:55 [Server] INFO at com.bgsoftware.wildstacker.command.CommandsHandler.onCommand(CommandsHandler.java:56) ~[WildStacker-2024.1-b53.jar:?]
12.05 00:40:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
12.05 00:40:55 [Server] INFO ... 29 more
12.05 00:41:22 [Server] INFO class net.minecraft.commands.arguments.ArgumentSignatures
12.05 00:41:22 [Server] INFO Nch001 issued server command: /pl
12.05 00:41:38 [Server] INFO [NBTAPI] [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
12.05 00:41:38 [Server] INFO [NBTAPI] [NBTAPI] NMS support 'MC1_20_R3' loaded!
12.05 00:41:38 [Server] INFO [NBTAPI] [NBTAPI] Using the plugin 'CommandPanels' to create a bStats instance!
12.05 00:42:30 [Server] INFO class net.minecraft.commands.arguments.ArgumentSignatures
12.05 00:42:30 [Server] INFO Puddington issued server command: /home dicey
12.05 00:42:42 [Server] INFO [NBTAPI] [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
12.05 00:42:42 [Server] INFO [NBTAPI] [NBTAPI] NMS support 'MC1_20_R3' loaded!
12.05 00:42:42 [Server] INFO [NBTAPI] [NBTAPI] Using the plugin 'Sellwand' to create a bStats instance!
12.05 00:43:20 [Server] INFO class net.minecraft.commands.arguments.ArgumentSignatures
12.05 00:43:20 [Server] INFO Puddington issued server command: /shop
12.05 00:43:43 [Server] INFO class net.minecraft.commands.arguments.ArgumentSignatures
12.05 00:43:43 [Server] INFO Puddington issued server command: /sellall hand
12.05 00:43:43 [Server] INFO Shop ➨ Puddington sold 1 x Cactus(FarmandFood.page1.items.39) for $1 with the sell all command.
12.05 00:44:11 [Server] INFO class net.minecraft.commands.arguments.ArgumentSignatures
12.05 00:44:11 [Server] INFO Puddington issued server command: /wb
12.05 00:44:17 [Server] INFO class net.minecraft.commands.arguments.ArgumentSignatures
12.05 00:44:17 [Server] INFO Nch001 issued server command: /ws give Nch001 egg blaze 12
`

### To Reproduce

/ws give <player> spawner <entity> <amount>

**Comment by Nch0001** [comment]
Ive reset the configs and everything

**Comment by Nch0001** [comment]
nvm issue with another plugin interacting

**Comment by Nch0001** [comment]
> @Nch0001 which plugin?

No worries issue was fixed didn't have compatibility with mine able spawners
