### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDeathEvent.<init>(org.bukkit.entity.LivingEntity, java.util.List, int)'

### ISSUE THREAD

**Issue by zuzu-a** [BG-Software-LLC/WildStacker#918]
### Minecraft's Version

Paper version 1.20.6-86-master@9bf4855 (2024-05-20T18:22:30Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### Plugin's Version

2024.1

### Describe the bug

I keep getting spammed by a WARN in the console.

### To Reproduce

This happened on install and as soon as I boot up the server. Unsure of what the issue is, it is plaguing my console.

### Additional Information

```
[20:19:39 WARN]: [WildStacker] Task #1164 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDeathEvent.<init>(org.bukkit.entity.LivingEntity, java.util.List, int)'
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:160) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1702) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1574) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[20:19:56 WARN]: [WildStacker] Task #1220 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDeathEvent.<init>(org.bukkit.entity.LivingEntity, java.util.List, int)'
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:160) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1702) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1574) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[20:20:17 WARN]: [WildStacker] Task #1280 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDeathEvent.<init>(org.bukkit.entity.LivingEntity, java.util.List, int)'
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:160) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1702) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1574) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[20:20:19 WARN]: [WildStacker] Task #1297 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.entity.EntityDeathEvent.<init>(org.bukkit.entity.LivingEntity, java.util.List, int)'
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:160) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1702) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1574) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
