### ISSUE TITLE
mcMMO NoSuchMethodError

### ISSUE THREAD

**Issue by TheAlm1ghty0** [BG-Software-LLC/WildStacker#921]
### Minecraft's Version

paper server 1.20.6

### Plugin's Version

WildStacker-2024.1

### Describe the bug

constantly in the server console im getting a warning that I don't fully understand.
```
[11:12:50 WARN]: [WildStacker] Task #863 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'com.gmail.nossr50.metadata.MetadataService com.gmail.nossr50.mcMMO.getMetadataService()'
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.hooks.McMMO210Hook.hasTag(McMMO210Hook.java:102) ~[WildStacker-2024.1.jar:?]
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.hooks.McMMO210Hook.isSpawnerEntity(McMMO210Hook.java:98) ~[WildStacker-2024.1.jar:?]
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.hooks.McMMO210Hook.handleDeath(McMMO210Hook.java:45) ~[WildStacker-2024.1.jar:?]
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyEntityDeathListeners$6(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyEntityDeathListeners(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:148) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
The task number will change but otherwise they are exactly the same

### To Reproduce

I assume you have mcMMO and WildStacker installed on the same server and you'd encounter the same problem

### Additional Information

I have a fair number of other plugins so its not definitely mcMMO, but that is what the error is saying so I assume that is the cause

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by deadspidervenom** [comment]
> Check out latest dev build, let me know if it is fixed

Tested on 1.20.6 Fixed
