### ISSUE TITLE
Cant kill snow golem

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BG-Software-LLC/WildStacker#934]
### Minecraft's Version

Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*

### Plugin's Version

WildStacker-2024.1-b66.jar

### Describe the bug

Snow golems are stuck with 0 health

```
08.07 02:00:50 [Server] WARN [WildStacker] Plugin WildStacker v2024.1-b64 generated an exception while executing task 1475816125
08.07 02:00:50 [Server] INFO java.lang.IllegalArgumentException: No enum constant EntityTypes.SNOW_GOLEM
08.07 02:00:50 [Server] INFO at WildStacker-2024.1-b64.jar/com.bgsoftware.wildstacker.utils.legacy.EntityTypes.fromEntity(EntityTypes.java:158) ~[WildStacker-2024.1-b64.jar:?]
08.07 02:00:50 [Server] INFO at WildStacker-2024.1-b64.jar/com.bgsoftware.wildstacker.handlers.LootHandler.getLootTable(LootHandler.java:178) ~[WildStacker-2024.1-b64.jar:?]
08.07 02:00:50 [Server] INFO at WildStacker-2024.1-b64.jar/com.bgsoftware.wildstacker.objects.WStackedEntity.getDrops(WStackedEntity.java:494) ~[WildStacker-2024.1-b64.jar:?]
08.07 02:00:50 [Server] INFO at WildStacker-2024.1-b64.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$simulateDeath$4(DeathSimulation.java:133) ~[WildStacker-2024.1-b64.jar:?]
08.07 02:00:50 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:50 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:50 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
08.07 02:00:50 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
08.07 02:00:50 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
08.07 02:00:50 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
08.07 02:00:51 [Server] WARN [WildStacker] Task #1475816124 for WildStacker v2024.1-b64 generated an exception
08.07 02:00:51 [Server] INFO java.lang.IllegalArgumentException: No enum constant EntityTypes.SNOW_GOLEM
08.07 02:00:51 [Server] INFO at WildStacker-2024.1-b64.jar/com.bgsoftware.wildstacker.utils.legacy.EntityTypes.fromEntity(EntityTypes.java:158) ~[WildStacker-2024.1-b64.jar:?]
08.07 02:00:51 [Server] INFO at WildStacker-2024.1-b64.jar/com.bgsoftware.wildstacker.objects.WStackedEntity.lambda$runUnstack$5(WStackedEntity.java:319) ~[WildStacker-2024.1-b64.jar:?]
08.07 02:00:51 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
08.07 02:00:51 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### To Reproduce

Try to kill snow golem

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Kryniowesegryderiusz** [comment]
Yes, fixed
