### ISSUE TITLE
no load plugins

### ISSUE THREAD

**Issue by lechatdeschats** [BG-Software-LLC/WildStacker#939]
### Minecraft's Version

[00:02:48 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### Plugin's Version

[00:03:10 INFO]: WildStacker version 2024.1-b71
[00:03:10 INFO]: Stacking drops, entities, blocks and spawners into one object!
[00:03:10 INFO]: Website: https://bg-software.com/
[00:03:10 INFO]: Author: Ome_R

### Describe the bug

the plugins do not load on a server in 1.20.1

error in my console : 

[23:58:27 INFO]: [WildStacker] The plugin doesn't support your minecraft version.
[23:58:27 INFO]: [WildStacker] Please try a different version.
[23:58:27 WARN]: com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid builtin nms handlers for the data version: 3465
[23:58:27 WARN]:        at WildStacker-2024.1-b71.jar//com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.getNMSPackageVersionName(NMSHandlersFactory.java:70)
[23:58:27 WARN]:        at WildStacker-2024.1-b71.jar//com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.createNMSLoader(NMSHandlersFactory.java:26)
[23:58:27 WARN]:        at WildStacker-2024.1-b71.jar//com.bgsoftware.wildstacker.WildStackerPlugin.loadNMSAdapter(WildStackerPlugin.java:213)
[23:58:27 WARN]:        at WildStacker-2024.1-b71.jar//com.bgsoftware.wildstacker.WildStackerPlugin.onLoad(WildStackerPlugin.java:96)
[23:58:27 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[23:58:27 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[23:58:27 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
[23:58:27 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[23:58:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510)
[23:58:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
[23:58:27 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[23:58:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[23:58:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[23:58:27 INFO]: [WildStacker] There was an error while loading the plugin.

### To Reproduce

start your server on 1.20.1 papermc with the plugins in version 2024.1-b71

**Comment by OmerBenGera** [comment]
Right.
Support to 1.20.1 was dropped. Update to 1.20.4 if you dont want to be affected by the new item nbt changes and still be able to use the plugin.
