### ISSUE TITLE
Console warning spam causing lag

### ISSUE THREAD

**Issue by Exteron01** [BG-Software-LLC/WildStacker#946]
### Minecraft's Version

1.20.1

### Plugin's Version

WildStacker version 2024.1

### Describe the bug

In the console it keeps spamming this error

[13:05:43 WARN]: [WildStacker] Task #5515753 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'com.gmail.nossr50.metadata.MetadataService com.gmail.nossr50.mcMMO.getMetadataService()'
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.hasTag(McMMO210Hook.java:102) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.isSpawnerEntity(McMMO210Hook.java:98) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.handleDeath(McMMO210Hook.java:45) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyEntityDeathListeners$6(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyEntityDeathListeners(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:148) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:05:50 WARN]: [WildStacker] Task #5517822 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'com.gmail.nossr50.metadata.MetadataService com.gmail.nossr50.mcMMO.getMetadataService()'
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.hasTag(McMMO210Hook.java:102) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.isSpawnerEntity(McMMO210Hook.java:98) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.handleDeath(McMMO210Hook.java:45) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyEntityDeathListeners$6(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyEntityDeathListeners(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:148) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:05:54 INFO]: [com.fastasyncworldedit.bukkit.listener.ChunkListener] [FAWE Tick Limiter] Detected and cancelled physics lag source at Location{world=CraftWorld{name=farmvilag},x=-1624.0,y=86.0,z=-205.0,pitch=0.0,yaw=0.0}
[13:05:54 WARN]: [WildStacker] Task #5518804 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'com.gmail.nossr50.metadata.MetadataService com.gmail.nossr50.mcMMO.getMetadataService()'
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.hasTag(McMMO210Hook.java:102) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.isSpawnerEntity(McMMO210Hook.java:98) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.handleDeath(McMMO210Hook.java:45) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyEntityDeathListeners$6(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyEntityDeathListeners(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:148) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:05:55 WARN]: [WildStacker] Task #5519205 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'com.gmail.nossr50.metadata.MetadataService com.gmail.nossr50.mcMMO.getMetadataService()'
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.hasTag(McMMO210Hook.java:102) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.isSpawnerEntity(McMMO210Hook.java:98) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.hooks.McMMO210Hook.handleDeath(McMMO210Hook.java:45) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyEntityDeathListeners$6(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyEntityDeathListeners(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
        at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:148) ~[WildStacker-2024.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

No idea, it just keeps spamming this

**Comment by OmerBenGera** [comment]
Update WildStacker, fixed already in recent builds :)

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
