### ISSUE TITLE
WildStacker wont work on 1.20.1

### ISSUE THREAD

**Issue by Xayanix** [BG-Software-LLC/WildStacker#951]
### Minecraft's Version

1.20.1

### Plugin's Version

latest dev build b75

### Describe the bug

```[23:47:26] [Server thread/INFO]: [WildStacker] Loading server plugin WildStacker v2024.2-b75
[23:47:26] [Server thread/INFO]: [WildStacker] The plugin doesn't support your minecraft version.
[23:47:26] [Server thread/INFO]: [WildStacker] Please try a different version.
[23:47:26] [Server thread/WARN]: com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid builtin nms handlers for the data version: 3465
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.getNMSPackageVersionName(NMSHandlersFactory.java:70)
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.createNMSLoader(NMSHandlersFactory.java:26)
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.WildStackerPlugin.loadNMSAdapter(WildStackerPlugin.java:213)
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.WildStackerPlugin.onLoad(WildStackerPlugin.java:96)
[23:47:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:97)
[23:47:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.enter(ServerPluginProviderStorage.java:76)
[23:47:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[23:47:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:516)
[23:47:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:285)
[23:47:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1108)
[23:47:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[23:47:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:47:26] [Server thread/INFO]: [WildStacker] There was an error while loading the plugin.```

### To Reproduce

```[23:47:26] [Server thread/INFO]: [WildStacker] Loading server plugin WildStacker v2024.2-b75
[23:47:26] [Server thread/INFO]: [WildStacker] The plugin doesn't support your minecraft version.
[23:47:26] [Server thread/INFO]: [WildStacker] Please try a different version.
[23:47:26] [Server thread/WARN]: com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSLoadException: Couldn't find valid builtin nms handlers for the data version: 3465
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.getNMSPackageVersionName(NMSHandlersFactory.java:70)
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.libs.com.bgsoftware.common.nmsloader.NMSHandlersFactory.createNMSLoader(NMSHandlersFactory.java:26)
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.WildStackerPlugin.loadNMSAdapter(WildStackerPlugin.java:213)
[23:47:26] [Server thread/WARN]: 	at WildStacker-2024.2-b75.jar//com.bgsoftware.wildstacker.WildStackerPlugin.onLoad(WildStackerPlugin.java:96)
[23:47:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:97)
[23:47:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.enter(ServerPluginProviderStorage.java:76)
[23:47:26] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[23:47:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:516)
[23:47:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:285)
[23:47:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1108)
[23:47:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[23:47:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:47:26] [Server thread/INFO]: [WildStacker] There was an error while loading the plugin.```

### Additional Information

_No response_

**Comment by OmerBenGera** [comment]
Not supported. Update to 1.20.4
