### ISSUE TITLE
error plugin - java.lang.IllegalArgumentException: No enum constant EntityTypes.BLOCK_DISPLAY

### ISSUE THREAD

**Issue by SoaresTI** [BG-Software-LLC/WildStacker#953]
### Minecraft's Version

version 1.21 purpur

### Plugin's Version

2024.2

### Describe the bug

[01:31:29] [Craft Scheduler Thread - 16724 - WildStacker/WARN]: [WildStacker] Plugin WildStacker v2024.1 generated an exception while executing task 221485566
java.lang.IllegalArgumentException: No enum constant EntityTypes.BLOCK_DISPLAY
	at com.bgsoftware.wildstacker.utils.legacy.EntityTypes.fromEntity(EntityTypes.java:156) ~[WildStacker-2024.1 (1).jar:?]
	at com.bgsoftware.wildstacker.handlers.LootHandler.getLootTable(LootHandler.java:253) ~[WildStacker-2024.1 (1).jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.getDrops(WStackedEntity.java:494) ~[WildStacker-2024.1 (1).jar:?]
	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$simulateDeath$4(DeathSimulation.java:132) ~[WildStacker-2024.1 (1).jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:31:29] [Craft Scheduler Thread - 16724 - SinceMarket/INFO]: [SinceMarket] Verificando ativações...
[01:31:29] [Server thread/WARN]: [WildStacker] Task #221485565 for WildStacker v2024.1 generated an exception
java.lang.IllegalArgumentException: No enum constant EntityTypes.BLOCK_DISPLAY
	at com.bgsoftware.wildstacker.utils.legacy.EntityTypes.fromEntity(EntityTypes.java:156) ~[WildStacker-2024.1 (1).jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedEntity.lambda$runUnstack$5(WStackedEntity.java:319) ~[WildStacker-2024.1 (1).jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

I can't find specific actions, it just keeps flooding the panel

**Comment by OmerBenGera** [comment]
Update the plugin - you're using 2024.1 and not 2024.2

**Comment by SoaresTI** [comment]
[10:42:02 WARN]: [WildStacker] Plugin WildStacker v2024.2 generated an exception while executing task 18634736
java.lang.IllegalArgumentException: No enum constant EntityTypes.BLOCK_DISPLAY
        at WildStacker-2024.2.jar/com.bgsoftware.wildstacker.utils.legacy.EntityTypes.fromEntity(EntityTypes.java:161) ~[WildStacker-2024.2.jar:?]
        at WildStacker-2024.2.jar/com.bgsoftware.wildstacker.handlers.LootHandler.getLootTable(LootHandler.java:178) ~[WildStacker-2024.2.jar:?]
        at WildStacker-2024.2.jar/com.bgsoftware.wildstacker.objects.WStackedEntity.getDrops(WStackedEntity.java:499) ~[WildStacker-2024.2.jar:?]
        at WildStacker-2024.2.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$simulateDeath$4(DeathSimulation.java:134) ~[WildStacker-2024.2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.21.jar:1.21-DEV-ee6983a]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself
For no reason, BlockDisplay is considered a living entity on your server.
Do you have any of these? Also, the error above can only happen if you damage an entity - how do you damage a block display?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
