### ISSUE TITLE
Epicspawners + WildStacker console thrown code

### ISSUE THREAD

**Issue by absthatsme** [BG-Software-LLC/WildStacker#964]
### Minecraft's Version

Paper.123 (1.21.1)

### Plugin's Version

Latest Version.

### Describe the bug

I killed a zombie stacked x6, and went down to 5, then spawner respawned mob and went back to 6 and threw code.

### To Reproduce

With Epic spawner's, acting as the spawner plugin, with yours disabled.

### Additional Information

22.10 06:55:36 [Server] WARN java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.bgsoftware.wildstacker.utils.data.structures.Fast2EnumsMap.get(java.lang.Enum, java.lang.Enum)" is null
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.core.hooks.stackers.WildStacker.getMinStackSize(WildStacker.java:77)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.core.hooks.EntityStackerManager.getMinStackSize(EntityStackerManager.java:78)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.core.world.SSpawner.spawn(SSpawner.java:66)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.spawners.spawner.PlacedSpawnerImpl.spawn(PlacedSpawnerImpl.java:167)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.spawners.spawner.option.SpawnOptionEntity.spawn(SpawnOptionEntity.java:90)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.spawners.spawner.SpawnerTierImpl.spawn(SpawnerTierImpl.java:101)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.spawners.spawner.PlacedSpawnerImpl.spawn(PlacedSpawnerImpl.java:126)
22.10 06:55:36 [Server] WARN at EpicSpawners-8.5.0.jar//com.craftaro.epicspawners.tasks.SpawnerSpawnTask.run(SpawnerSpawnTask.java:65)
22.10 06:55:36 [Server] WARN at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
22.10 06:55:36 [Server] WARN at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
22.10 06:55:36 [Server] WARN at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724)
22.10 06:55:36 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
22.10 06:55:36 [Server] WARN at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596)
22.10 06:55:36 [Server] WARN at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302)
22.10 06:55:36 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
22.10 06:55:36 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by absthatsme** [comment]
Also whenever I shift click buckets into a chest, they disappear. and I blacklisted them from stacking.

**Comment by OmerBenGera** [comment]
Hey, what is your discord?

**Comment by absthatsme** [comment]
absthatsme

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by absthatsme** [comment]
absthatsme

**Comment by OmerBenGera** [comment]
Join our discord server https://bg-software.com/discord/
