### ISSUE TITLE
ChunkLoadEvent

### ISSUE THREAD

**Issue by Aspreims** [BG-Software-LLC/WildStacker#970]
### Minecraft's Version

1.21.1 SparklyPaper

### Plugin's Version

b91

### Describe the bug

When I start the plugin, as soon as I start

[10:43:40] [Server thread/ERROR]: [ErrorFilter] Could not pass event ChunkLoadEvent to WildStacker v2024.3-b91

### To Reproduce

run plugin

**Comment by Aspreims** [comment]
This is the entire error.

**Comment by Aspreims** [comment]
all logs https://hastebin.skyra.pw/supukadoto.md

**Comment by Aspreims** [comment]
[12:44:02] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to WildStacker v2024.3-b91
java.lang.NoSuchFieldError: Class net.minecraft.server.level.ServerLevel does not have member field 'java.util.List r'
	at WildStacker-2024.3-b91-1731145357373.jar/com.bgsoftware.wildstacker.nms.v1_21.NMSSpawnersImpl.updateStackedSpawners(NMSSpawnersImpl.java:96) ~[WildStacker-2024.3-b91-1731145357373.jar:?]
	at WildStacker-2024.3-b91-1731145357373.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.loadSpawners(SystemHandler.java:770) ~[WildStacker-2024.3-b91-1731145357373.jar:?]
	at WildStacker-2024.3-b91-1731145357373.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkLoad(SystemHandler.java:816) ~[WildStacker-2024.3-b91-1731145357373.jar:?]
	at WildStacker-2024.3-b91-1731145357373.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkLoad(SystemHandler.java:803) ~[WildStacker-2024.3-b91-1731145357373.jar:?]
	at WildStacker-2024.3-b91-1731145357373.jar/com.bgsoftware.wildstacker.listeners.ChunksListener.onChunkLoad(ChunksListener.java:30) ~[WildStacker-2024.3-b91-1731145357373.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor801.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-DEV-8c40f73]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:673) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1281) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:341) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:743) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:376) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:397) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1518) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1510) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1632) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1307) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by OmerBenGera** [comment]
Check out latest dev build, should work now on SparklyPaper.
In general, I do not support custom coded forks of Paper, however I decided in this case to add support to this specific fork.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
