### ISSUE TITLE
Folia bug

### ISSUE THREAD

**Issue by WhyZerVellasskx** [BG-Software-LLC/WildStacker#978]
### Minecraft's Version

folia 1.20.6

### Plugin's Version

2024.1 (folia branch)

### Describe the bug

Hello, I have compiled a plugin from the sources on the folia branch, launched it and it gives an error, can you please fix it

### To Reproduce

1. build plugin
2. starting server xd 

### Additional Information

[14:31:19] [Region Scheduler Thread #0/INFO]: Initialised world 'world_the_end'
[14:31:19] [Region Scheduler Thread #2/ERROR]: Could not pass event ChunkLoadEvent to WildStacker v2024.1
java.lang.NoSuchFieldError: Class net.minecraft.server.level.ServerLevel does not have member field 'java.util.List r'
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.nms.v1_20_4.NMSSpawnersImpl.updateStackedSpawners(NMSSpawnersImpl.java:96) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.loadSpawners(SystemHandler.java:782) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkLoad(SystemHandler.java:828) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkLoad(SystemHandler.java:815) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.listeners.ChunksListener.onChunkLoad(ChunksListener.java:30) ~[WildStacker-2024.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor213.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-9a19e42]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:792) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:744) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1538) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1516) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1468) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:897) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:62) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:429) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:953) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1871) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[14:31:19] [Region Scheduler Thread #1/INFO]: Initialised world 'spawn'
[14:31:19] [Region Scheduler Thread #1/ERROR]: Could not pass event ChunkLoadEvent to WildStacker v2024.1
java.lang.NoSuchFieldError: Class net.minecraft.server.level.ServerLevel does not have member field 'java.util.List r'
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.nms.v1_20_4.NMSSpawnersImpl.updateStackedSpawners(NMSSpawnersImpl.java:96) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.loadSpawners(SystemHandler.java:782) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkLoad(SystemHandler.java:828) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkLoad(SystemHandler.java:815) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.listeners.ChunksListener.onChunkLoad(ChunksListener.java:30) ~[WildStacker-2024.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor213.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-9a19e42]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:792) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:744) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1538) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1516) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1468) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:897) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:62) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:429) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:953) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1871) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-9a19e42]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by OmerBenGera** [comment]
Folia is not supported.
Not sure why it was even loaded.
