### ISSUE TITLE
Error occurred while enabling WildStacker v2024.4-b113

### ISSUE THREAD

**Issue by MeesterMaarten** [BG-Software-LLC/WildStacker#998]
### Minecraft's Version

Paper | 1.21.4 | Build 63 (28/12/2024)

### Plugin's Version

WildStacker v2024.4-b113

### Describe the bug

Error occurred while enabling WildStacker v2024.4-b113 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.enchantments.CraftEnchantment.<init>(org.bukkit.NamespacedKey, net.minecraft.world.item.enchantment.Enchantment)'
        at WildStacker-2024.4-b113.jar/com.bgsoftware.wildstacker.nms.v1_21_4.enchantment.GlowEnchantment.<init>(GlowEnchantment.java:110) ~[WildStacker-2024.4-b113.jar:?]
        at WildStacker-2024.4-b113.jar/com.bgsoftware.wildstacker.nms.v1_21_4.NMSAdapterImpl.getGlowEnchant(NMSAdapterImpl.java:82) ~[WildStacker-2024.4-b113.jar:?]
        at WildStacker-2024.4-b113.jar/com.bgsoftware.wildstacker.nms.v1_21_4.NMSAdapterImpl.createGlowEnchantment(NMSAdapterImpl.java:87) ~[WildStacker-2024.4-b113.jar:?]
        at WildStacker-2024.4-b113.jar/com.bgsoftware.wildstacker.utils.items.GlowEnchantment.registerEnchantment(GlowEnchantment.java:13) ~[WildStacker-2024.4-b113.jar:?]
        at WildStacker-2024.4-b113.jar/com.bgsoftware.wildstacker.WildStackerPlugin.onEnable(WildStackerPlugin.java:153) ~[WildStacker-2024.4-b113.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:35:58 INFO]: [WildStacker] Disabling WildStacker v2024.4-b113
[22:35:58 INFO]: [WildStacker] Cancelling tasks...
[22:35:58 INFO]: [WildStacker] Shutting down stacking service...
[22:35:58 INFO]: [WildStacker] Performing entity&items save
[22:35:58 ERROR]: Error occurred while disabling WildStacker v2024.4-b113
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkUnload(org.bukkit.Chunk, int)" because "this.systemManager" is null
        at WildStacker-2024.4-b113.jar/com.bgsoftware.wildstacker.WildStackerPlugin.onDisable(WildStackerPlugin.java:124) ~[WildStacker-2024.4-b113.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-63-feb8756]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

Plugin does not load when starting the server.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Sckaletz** [comment]
I can confirm it's still not working on build 114. It's the same issue with WildTools.

**Comment by MeesterMaarten** [comment]
I can also confirm that the plugin does not start with dev. building 114.

**Comment by smscentras** [comment]
no fix :(

**Comment by smscentras** [comment]
BIG flood in console, 20+ times:

`[Server thread/ERROR]: Could not pass event EntityDamageEvent to WildStacker v2024.4-b114
java.lang.ClassCastException: class org.bukkit.event.HandlerList cannot be cast to class com.bgsoftware.wildstacker.utils.events.BiHandlerList (org.bukkit.event.HandlerList is in unnamed module of loader java.net.URLClassLoader @497470ed; com.bgsoftware.wildstacker.utils.events.BiHandlerList is in unnamed module of loader 'WildStacker-2024.4-b114.jar' @7ba4cfe5)
	at WildStacker-2024.4-b114.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.recallDamageEvent(EntitiesListener.java:215) ~[WildStacker-2024.4-b114.jar:?]
	at WildStacker-2024.4-b114.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:230) ~[WildStacker-2024.4-b114.jar:?]
	at WildStacker-2024.4-b114.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:211) ~[WildStacker-2024.4-b114.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1219) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1198) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1101) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1257) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2420) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1553) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.animal.IronGolem.hurt(IronGolem.java:267) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:927) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:446) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Mob.baseTick(Mob.java:372) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.tick(Entity.java:880) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3226) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Mob.tick(Mob.java:469) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1330) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:761) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1851) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by smscentras** [comment]
Same problem on **b116**:

`[Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to WildStacker v2024.4-b116
java.lang.ClassCastException: class org.bukkit.event.HandlerList cannot be cast to class com.bgsoftware.wildstacker.utils.events.BiHandlerList (org.bukkit.event.HandlerList is in unnamed module of loader java.net.URLClassLoader @497470ed; com.bgsoftware.wildstacker.utils.events.BiHandlerList is in unnamed module of loader 'WildStacker-2024.4-b116.jar' @6c8b4477)
	at WildStacker-2024.4-b116.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.recallDamageEvent(EntitiesListener.java:215) ~[WildStacker-2024.4-b116.jar:?]
	at WildStacker-2024.4-b116.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:230) ~[WildStacker-2024.4-b116.jar:?]
	at WildStacker-2024.4-b116.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:211) ~[WildStacker-2024.4-b116.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor107.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1219) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1214) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1158) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1101) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1257) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2420) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1553) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.animal.IronGolem.hurt(IronGolem.java:267) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.block.CampfireBlock.entityInside(CampfireBlock.java:109) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:1230) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1712) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1371) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.move(Entity.java:1307) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:3022) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3619) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:708) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.animal.IronGolem.aiStep(IronGolem.java:156) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3267) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Mob.tick(Mob.java:469) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1330) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:761) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1851) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by OmerBenGera** [comment]
Errors regarding the enchantment should be fixed
Make sure you update both the plugins and paper.

**Comment by smscentras** [comment]
I can't update Paper, because have 100+1 plugins and there is some which are not working on 1.21.4

**Comment by OmerBenGera** [comment]
> I can't update Paper, because have 100+1 plugins and there is some which are not working on 1.21.4

The error of the BiHandlerList is not related.
Check out #993 and provide your config file in there as well as the entire session logs

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
